AcrisiaMountains_MapScripts::
	.byte 0


AcrisiaMountains_Sign_GymSign::
# 5 "data/maps/AcrisiaMountains/scripts.pory"
	lock
# 6 "data/maps/AcrisiaMountains/scripts.pory"
	msgbox AcrisiaMountains_Sign_GymSign_Text_0
# 7 "data/maps/AcrisiaMountains/scripts.pory"
	closemessage
# 8 "data/maps/AcrisiaMountains/scripts.pory"
	release
	end


AcrisiaMountains_Sign_GymSign_Text_0:
# 6 "data/maps/AcrisiaMountains/scripts.pory"
	.string "Gym Leader: Mattaios\n"
	.string "The Ever-Working Rocksmith$"
