SofosCity_MapScripts::
	.byte 0


SofosCity_EventScript_GameCornerSign::
# 5 "data/maps/SofosCity/scripts.pory"
	lock
# 6 "data/maps/SofosCity/scripts.pory"
	msgbox SofosCity_EventScript_GameCornerSign_Text_0
# 7 "data/maps/SofosCity/scripts.pory"
	closemessage
# 8 "data/maps/SofosCity/scripts.pory"
	release
	end


SofosCity_EventScript_GameCornerSign_Text_0:
# 6 "data/maps/SofosCity/scripts.pory"
	.string "Sofos City Game Corner\p"
	.string "Play Pinball, Get Prizes!$"
