# 1 "data/maps/Route133/scripts.pory"

# 2 "data/maps/Route133/scripts.pory"
Route133_MapScripts::
# 3 "data/maps/Route133/scripts.pory"
	.byte 0
# 4 "data/maps/Route133/scripts.pory"

# 5 "data/maps/Route133/scripts.pory"
Route133_EventScript_Franklin::
# 6 "data/maps/Route133/scripts.pory"
	trainerbattle_single TRAINER_FRANKLIN, Route133_Text_FranklinIntro, Route133_Text_FranklinDefeat
# 7 "data/maps/Route133/scripts.pory"
	msgbox_mugshot Route133_Text_FranklinPostBattle, MSGBOX_AUTOCLOSE, MUGSHOT_SWIMMERM
# 8 "data/maps/Route133/scripts.pory"
	end
# 9 "data/maps/Route133/scripts.pory"

# 10 "data/maps/Route133/scripts.pory"
Route133_EventScript_Debra::
# 11 "data/maps/Route133/scripts.pory"
	trainerbattle_single TRAINER_DEBRA, Route133_Text_DebraIntro, Route133_Text_DebraDefeat
# 12 "data/maps/Route133/scripts.pory"
	msgbox_mugshot Route133_Text_DebraPostBattle, MSGBOX_AUTOCLOSE, MUGSHOT_SWIMMERF
# 13 "data/maps/Route133/scripts.pory"
	end
# 14 "data/maps/Route133/scripts.pory"

# 15 "data/maps/Route133/scripts.pory"
Route133_EventScript_Linda::
# 16 "data/maps/Route133/scripts.pory"
	trainerbattle_single TRAINER_LINDA, Route133_Text_LindaIntro, Route133_Text_LindaDefeat
# 17 "data/maps/Route133/scripts.pory"
	msgbox_mugshot Route133_Text_LindaPostBattle, MSGBOX_AUTOCLOSE, MUGSHOT_SWIMMERF
# 18 "data/maps/Route133/scripts.pory"
	end
# 19 "data/maps/Route133/scripts.pory"

# 20 "data/maps/Route133/scripts.pory"
Route133_EventScript_Warren::
# 21 "data/maps/Route133/scripts.pory"
	trainerbattle_single TRAINER_WARREN, Route133_Text_WarrenIntro, Route133_Text_WarrenDefeat
# 22 "data/maps/Route133/scripts.pory"
	msgbox_mugshot Route133_Text_WarrenPostBattle, MSGBOX_AUTOCLOSE, MUGSHOT_COOLTRAINER_M
# 23 "data/maps/Route133/scripts.pory"
	end
# 24 "data/maps/Route133/scripts.pory"

# 25 "data/maps/Route133/scripts.pory"
Route133_EventScript_Beck::
# 26 "data/maps/Route133/scripts.pory"
	trainerbattle_single TRAINER_BECK, Route133_Text_BeckIntro, Route133_Text_BeckDefeat
# 27 "data/maps/Route133/scripts.pory"
	msgbox_mugshot Route133_Text_BeckPostBattle, MSGBOX_AUTOCLOSE, MUGSHOT_BIRD_KEEPER
# 28 "data/maps/Route133/scripts.pory"
	end
# 29 "data/maps/Route133/scripts.pory"

# 30 "data/maps/Route133/scripts.pory"
Route133_EventScript_Mollie::
# 31 "data/maps/Route133/scripts.pory"
	trainerbattle_single TRAINER_MOLLIE, Route133_Text_MollieIntro, Route133_Text_MollieDefeat
# 32 "data/maps/Route133/scripts.pory"
	msgbox_mugshot Route133_Text_MolliePostBattle, MSGBOX_AUTOCLOSE, MUGSHOT_EXPERTF
# 33 "data/maps/Route133/scripts.pory"
	end
# 34 "data/maps/Route133/scripts.pory"

# 35 "data/maps/Route133/scripts.pory"
Route133_EventScript_Conor::
# 36 "data/maps/Route133/scripts.pory"
	trainerbattle_single TRAINER_CONOR, Route133_Text_ConorIntro, Route133_Text_ConorDefeat
# 37 "data/maps/Route133/scripts.pory"
	msgbox_mugshot Route133_Text_ConorPostBattle, MSGBOX_AUTOCLOSE, MUGSHOT_EXPERTM
# 38 "data/maps/Route133/scripts.pory"
	end
