#ifndef GUARD_CONSTANTS_DECORATIONS_H
#define GUARD_CONSTANTS_DECORATIONS_H

#define DECOR_NONE             0
#define DECOR_SMALL_DESK       1
#define DECOR_POKEMON_DESK     2
#define DECOR_HEAVY_DESK       3
#define DECOR_RAGGED_DESK      4
#define DECOR_COMFORT_DESK     5
#define DECOR_PRETTY_DESK      6
#define DECOR_BRICK_DESK       7
#define DECOR_CAMP_DESK        8
#define DECOR_HARD_DESK        9
#define DECOR_SMALL_CHAIR      10
#define DECOR_POKEMON_CHAIR    11
#define DECOR_HEAVY_CHAIR      12
#define DECOR_PRETTY_CHAIR     13
#define DECOR_COMFORT_CHAIR    14
#define DECOR_RAGGED_CHAIR     15
#define DECOR_BRICK_CHAIR      16
#define DECOR_CAMP_CHAIR       17
#define DECOR_HARD_CHAIR       18
#define DECOR_RED_PLANT        19
#define DECOR_TROPICAL_PLANT   20
#define DECOR_PRETTY_FLOWERS   21
#define DECOR_COLORFUL_PLANT   22
#define DECOR_BIG_PLANT        23
#define DECOR_GORGEOUS_PLANT   24
#define DECOR_RED_BRICK        25
#define DECOR_YELLOW_BRICK     26
#define DECOR_BLUE_BRICK       27
#define DECOR_RED_BALLOON      28
#define DECOR_BLUE_BALLOON     29
#define DECOR_YELLOW_BALLOON   30
#define DECOR_ENTERTAINMENT_CENTER        31 // replaces RED_TENT
#define DECOR_POKEBALL_STATION 32 // replaces BLUE_TENT
#define DECOR_SHRINE           33 // replaces SOLID_BOARD. DO NOT GIVE TO PLAYER IT'S BROKEN FOR SOME REASON SIGH
#define DECOR_SLIDE            34
#define DECOR_FENCE_LENGTH     35
#define DECOR_FENCE_WIDTH      36
#define DECOR_TIRE             37
#define DECOR_STAND            38
#define DECOR_MINOTAUROS_PLAQUE  39 // replaces MUD_BALL, reward for something on Kaptara Island probably
#define DECOR_BREAKABLE_DOOR   40
#define DECOR_SAND_ORNAMENT    41
#define DECOR_SILVER_SHIELD    42
#define DECOR_GOLD_SHIELD      43
#define DECOR_GLASS_ORNAMENT   44
#define DECOR_TV               45
#define DECOR_ROUND_TV         46
#define DECOR_CUTE_TV          47
#define DECOR_GLITTER_MAT      48
#define DECOR_JUMP_MAT         49
#define DECOR_SPIN_MAT         50
#define DECOR_C_LOW_NOTE_MAT   51
#define DECOR_D_NOTE_MAT       52
#define DECOR_E_NOTE_MAT       53
#define DECOR_F_NOTE_MAT       54
#define DECOR_G_NOTE_MAT       55
#define DECOR_A_NOTE_MAT       56
#define DECOR_B_NOTE_MAT       57
#define DECOR_C_HIGH_NOTE_MAT  58
#define DECOR_SURF_MAT         59
#define DECOR_THUNDER_MAT      60
#define DECOR_FIRE_BLAST_MAT   61
#define DECOR_POWDER_SNOW_MAT  62
#define DECOR_ATTRACT_MAT      63
#define DECOR_FISSURE_MAT      64
#define DECOR_SPIKES_MAT       65
#define DECOR_BALL_POSTER      66
#define DECOR_GREEN_POSTER     67
#define DECOR_RED_POSTER       68
#define DECOR_BLUE_POSTER      69
#define DECOR_DRAGON_POSTER    70 // replaces CUTE_POSTER, has Dragonair icon
#define DECOR_PIKA_POSTER      71
#define DECOR_PUPPY_POSTER     72 // replaces LONG_POSTER; shows Hisuian and Kantonian Growlithe
#define DECOR_SEA_POSTER       73
#define DECOR_SKY_POSTER       74
#define DECOR_SUNSET_POSTER    75 // replaces KISS_POSTER; shows version of title screen sunset and ruins
#define DECOR_PICHU_DOLL       76
#define DECOR_PIKACHU_DOLL     77
#define DECOR_MARILL_DOLL      78 // NEEDS REPLACEMENT
#define DECOR_TOGEPI_DOLL      79
#define DECOR_CYNDAQUIL_DOLL   80
#define DECOR_CHIKORITA_DOLL   81
#define DECOR_TOTODILE_DOLL    82
#define DECOR_JIGGLYPUFF_DOLL  83
#define DECOR_MEOWTH_DOLL      84
#define DECOR_CLEFAIRY_DOLL    85
#define DECOR_DITTO_DOLL       86 // NEEDS REPLACEMENT
#define DECOR_SMOOCHUM_DOLL    87 // NEEDS REPLACEMENT
#define DECOR_TREECKO_DOLL     88 // NEEDS REPLACEMENT
#define DECOR_TORCHIC_DOLL     89 // NEEDS REPLACEMENT
#define DECOR_MUDKIP_DOLL      90 // NEEDS REPLACEMENT
#define DECOR_DUSKULL_DOLL     91
#define DECOR_WYNAUT_DOLL      92 // NEEDS REPLACEMENT
#define DECOR_BALTOY_DOLL      93
#define DECOR_KECLEON_DOLL     94
#define DECOR_AZURILL_DOLL     95 // NEEDS REPLACEMENT
#define DECOR_SKITTY_DOLL      96 // NEEDS REPLACEMENT
#define DECOR_SWABLU_DOLL      97
#define DECOR_GULPIN_DOLL      98 // NEEDS REPLACEMENT
#define DECOR_LOTAD_DOLL       99 // NEEDS REPLACEMENT
#define DECOR_SEEDOT_DOLL      100 // NEEDS REPLACEMENT
#define DECOR_PIKA_CUSHION     101
#define DECOR_ROUND_CUSHION    102
#define DECOR_KISS_CUSHION     103
#define DECOR_ZIGZAG_CUSHION   104
#define DECOR_SPIN_CUSHION     105
#define DECOR_DIAMOND_CUSHION  106
#define DECOR_BALL_CUSHION     107
#define DECOR_GRASS_CUSHION    108
#define DECOR_FIRE_CUSHION     109
#define DECOR_WATER_CUSHION    110
#define DECOR_SNORLAX_DOLL     111 // NEEDS REPLACEMENT
#define DECOR_RHYDON_DOLL      112 // NEEDS REPLACEMENT
#define DECOR_LAPRAS_DOLL      113
#define DECOR_VENUSAUR_DOLL    114 // NEEDS REPLACEMENT
#define DECOR_CHARIZARD_DOLL   115 // NEEDS REPLACEMENT
#define DECOR_BLASTOISE_DOLL   116 // NEEDS REPLACEMENT
#define DECOR_WAILMER_DOLL     117
#define DECOR_REGIROCK_DOLL    118 // NEEDS REPLACEMENT
#define DECOR_REGICE_DOLL      119 // NEEDS REPLACEMENT
#define DECOR_REGISTEEL_DOLL   120 // NEEDS REPLACEMENT
#define DECOR_SMALL_FLOWER_BOX 121
#define DECOR_LARGE_BED        122
#define DECOR_PATTERNED_BED    123
#define DECOR_BOOK_AND_QUILL   124
#define NUM_DECORATIONS DECOR_BOOK_AND_QUILL

#endif  // GUARD_CONSTANTS_DECORATIONS_H
