#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#define OBJ_EVENT_GFX_BRENDAN_NORMAL               0
#define OBJ_EVENT_GFX_BRENDAN_MACH_BIKE            1
#define OBJ_EVENT_GFX_BRENDAN_SURFING              2
#define OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE           3
#define OBJ_EVENT_GFX_QUINTY_PLUMP                 4
#define OBJ_EVENT_GFX_NINJA_BOY                    5
#define OBJ_EVENT_GFX_TWIN                         6
#define OBJ_EVENT_GFX_BOY_1                        7
#define OBJ_EVENT_GFX_GIRL_1                       8
#define OBJ_EVENT_GFX_BOY_2                        9
#define OBJ_EVENT_GFX_GIRL_2                      10
#define OBJ_EVENT_GFX_LITTLE_BOY                  11
#define OBJ_EVENT_GFX_LITTLE_GIRL                 12
#define OBJ_EVENT_GFX_BOY_3                       13
#define OBJ_EVENT_GFX_GIRL_3                      14
#define OBJ_EVENT_GFX_RICH_BOY                    15
#define OBJ_EVENT_GFX_WOMAN_1                     16
#define OBJ_EVENT_GFX_FAT_MAN                     17
#define OBJ_EVENT_GFX_POKEFAN_F                   18
#define OBJ_EVENT_GFX_MAN_1                       19
#define OBJ_EVENT_GFX_WOMAN_2                     20
#define OBJ_EVENT_GFX_EXPERT_M                    21
#define OBJ_EVENT_GFX_EXPERT_F                    22
#define OBJ_EVENT_GFX_MAN_2                       23
#define OBJ_EVENT_GFX_WOMAN_3                     24
#define OBJ_EVENT_GFX_POKEFAN_M                   25
#define OBJ_EVENT_GFX_WOMAN_4                     26
#define OBJ_EVENT_GFX_COOK                        27
#define OBJ_EVENT_GFX_FARMER                      28
#define OBJ_EVENT_GFX_OLD_MAN                     29
#define OBJ_EVENT_GFX_OLD_WOMAN                   30
#define OBJ_EVENT_GFX_CAMPER                      31
#define OBJ_EVENT_GFX_PICNICKER                   32
#define OBJ_EVENT_GFX_MAN_3                       33
#define OBJ_EVENT_GFX_WOMAN_5                     34
#define OBJ_EVENT_GFX_YOUNGSTER                   35
#define OBJ_EVENT_GFX_BUG_CATCHER                 36
#define OBJ_EVENT_GFX_PSYCHIC_M                   37
#define OBJ_EVENT_GFX_SCHOOL_KID_M                38
#define OBJ_EVENT_GFX_MANIAC                      39
#define OBJ_EVENT_GFX_HEX_MANIAC                  40
#define OBJ_EVENT_GFX_RAYQUAZA_STILL              41
#define OBJ_EVENT_GFX_SWIMMER_M                   42
#define OBJ_EVENT_GFX_SWIMMER_F                   43
#define OBJ_EVENT_GFX_BLACK_BELT                  44
#define OBJ_EVENT_GFX_BEAUTY                      45
#define OBJ_EVENT_GFX_SCIENTIST_1                 46
#define OBJ_EVENT_GFX_LASS                        47
#define OBJ_EVENT_GFX_GENTLEMAN                   48
#define OBJ_EVENT_GFX_SAILOR                      49
#define OBJ_EVENT_GFX_FISHERMAN                   50
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M        51
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F        52
#define OBJ_EVENT_GFX_TUBER_F                     53
#define OBJ_EVENT_GFX_TUBER_M                     54
#define OBJ_EVENT_GFX_HIKER                       55
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M        56
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F        57
#define OBJ_EVENT_GFX_NURSE                       58
#define OBJ_EVENT_GFX_ITEM_BALL                   59
#define OBJ_EVENT_GFX_BERRY_TREE                  60
#define OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES     61
#define OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES      62
#define OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE           63
#define OBJ_EVENT_GFX_PROF_ELIA                   64
#define OBJ_EVENT_GFX_MAN_4                       65
#define OBJ_EVENT_GFX_MAN_5                       66
#define OBJ_EVENT_GFX_REPORTER_M                  67
#define OBJ_EVENT_GFX_REPORTER_F                  68
#define OBJ_EVENT_GFX_BARD                        69
#define OBJ_EVENT_GFX_ANABEL                      70
#define OBJ_EVENT_GFX_TUCKER                      71
#define OBJ_EVENT_GFX_GRETA                       72
#define OBJ_EVENT_GFX_SPENSER                     73
#define OBJ_EVENT_GFX_NOLAND                      74
#define OBJ_EVENT_GFX_LUCY                        75
#define OBJ_EVENT_GFX_UNUSED_NATU_DOLL            76
#define OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL       77
#define OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL        78
#define OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL          79
#define OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL         80
#define OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL        81
#define OBJ_EVENT_GFX_CUTTABLE_TREE               82
#define OBJ_EVENT_GFX_MART_EMPLOYEE               83
#define OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN          84
#define OBJ_EVENT_GFX_TEALA                       85
#define OBJ_EVENT_GFX_BREAKABLE_ROCK              86
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER            87
#define OBJ_EVENT_GFX_MR_BRINEYS_BOAT             88
#define OBJ_EVENT_GFX_MAY_NORMAL                  89
#define OBJ_EVENT_GFX_MAY_MACH_BIKE               90
#define OBJ_EVENT_GFX_MAY_ACRO_BIKE               91
#define OBJ_EVENT_GFX_MAY_SURFING                 92
#define OBJ_EVENT_GFX_MAY_FIELD_MOVE              93
#define OBJ_EVENT_GFX_TRUCK                       94
#define OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX       95
#define OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY        96
#define OBJ_EVENT_GFX_BIRCHS_BAG                  97
#define OBJ_EVENT_GFX_ZIGZAGOON_1                 98
#define OBJ_EVENT_GFX_ARTIST                      99
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL       100
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE    101
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE    102
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING      103
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE   104
#define OBJ_EVENT_GFX_RIVAL_MAY_NORMAL           105
#define OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE        106
#define OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE        107
#define OBJ_EVENT_GFX_RIVAL_MAY_SURFING          108
#define OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE       109
#define OBJ_EVENT_GFX_TOGA_GIRL                  110 // replaces cameraman
#define OBJ_EVENT_GFX_BRENDAN_UNDERWATER         111
#define OBJ_EVENT_GFX_MAY_UNDERWATER             112
#define OBJ_EVENT_GFX_MOVING_BOX                 113
#define OBJ_EVENT_GFX_CABLE_CAR                  114
#define OBJ_EVENT_GFX_SCIENTIST_2                115
#define OBJ_EVENT_GFX_CONSTRUCTION_WORKER        116 // replaces uhhhh something else idk
#define OBJ_EVENT_GFX_CHIMERA_MEMBER_M     117 // replaces AQUA_MEMBER_M
#define OBJ_EVENT_GFX_CHIMERA_MEMBER_F   118 // replaces AQUA_MEMBER_F
#define OBJ_EVENT_GFX_MAGMA_MEMBER_M             119
#define OBJ_EVENT_GFX_MAGMA_MEMBER_F             120
#define OBJ_EVENT_GFX_SIDNEY                     121
#define OBJ_EVENT_GFX_PHOEBE                     122
#define OBJ_EVENT_GFX_GLACIA                     123
#define OBJ_EVENT_GFX_DRAKE                      124
#define OBJ_EVENT_GFX_SABELLA                    125 // Gym Leader 3, in Pythios Town (replaces Roxanne gfx)
#define OBJ_EVENT_GFX_DEO                        126 // Gym Leader 1, in Jusmail Town (replacess Brawly gfx)
#define OBJ_EVENT_GFX_MATTAIOS                   127 // Gym Leader 2, in Acrisia Mountains / Discus Forge (replaces Wattson gfx)
#define OBJ_EVENT_GFX_MENESWO                   128 // Gym Leader 4, in Sofos City (replaces Flannery)
#define OBJ_EVENT_GFX_THYRSUS                    129 // Gym Leader 5, in Myrrini Island (replaces Norman)
#define OBJ_EVENT_GFX_WINONA                     130
#define OBJ_EVENT_GFX_LIZA                       131
#define OBJ_EVENT_GFX_TATE                       132
#define OBJ_EVENT_GFX_WALLACE                    133
#define OBJ_EVENT_GFX_RANIA                      134 // replaces GFX_STEVEN
#define OBJ_EVENT_GFX_NIKO                       135 // replaces GFX_WALLY
#define OBJ_EVENT_GFX_LITTLE_BOY_3               136
#define OBJ_EVENT_GFX_BRENDAN_FISHING            137
#define OBJ_EVENT_GFX_MAY_FISHING                138
#define OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN      139
#define OBJ_EVENT_GFX_THE_DELPHIS                   140
#define OBJ_EVENT_GFX_SUBMARINE_SHADOW           141
#define OBJ_EVENT_GFX_MIMIKYU_DOLL               142
#define OBJ_EVENT_GFX_PIKACHU_DOLL               143
#define OBJ_EVENT_GFX_CRABRAWLER_DOLL            144
#define OBJ_EVENT_GFX_TOGEPI_DOLL                145
#define OBJ_EVENT_GFX_CYNDAQUIL_DOLL             146
#define OBJ_EVENT_GFX_CHIKORITA_DOLL             147
#define OBJ_EVENT_GFX_TOTODILE_DOLL              148
#define OBJ_EVENT_GFX_JIGGLYPUFF_DOLL            149
#define OBJ_EVENT_GFX_MEOWTH_DOLL                150
#define OBJ_EVENT_GFX_IMPIDIMP_DOLL              151
#define OBJ_EVENT_GFX_EGG_DOLL                   152
#define OBJ_EVENT_GFX_ARCHEN_DOLL                153
#define OBJ_EVENT_GFX_CHESPIN_DOLL               154
#define OBJ_EVENT_GFX_FENNEKIN_DOLL              155
#define OBJ_EVENT_GFX_FROAKIE_DOLL               156
#define OBJ_EVENT_GFX_DUSKULL_DOLL               157
#define OBJ_EVENT_GFX_TIRTOUGA_DOLL              158
#define OBJ_EVENT_GFX_BALTOY_DOLL                159
#define OBJ_EVENT_GFX_KECLEON_DOLL               160
#define OBJ_EVENT_GFX_STUFFUL_DOLL               161
#define OBJ_EVENT_GFX_APPLIN_DOLL                162
#define OBJ_EVENT_GFX_SWABLU_DOLL                163
#define OBJ_EVENT_GFX_BOUNSWEET_DOLL             164
#define OBJ_EVENT_GFX_SKIDDO_DOLL                165
#define OBJ_EVENT_GFX_ROCKRUFF_DOLL              166
#define OBJ_EVENT_GFX_PIKA_CUSHION               167
#define OBJ_EVENT_GFX_ROUND_CUSHION              168
#define OBJ_EVENT_GFX_KISS_CUSHION               169
#define OBJ_EVENT_GFX_ZIGZAG_CUSHION             170
#define OBJ_EVENT_GFX_SPIN_CUSHION               171
#define OBJ_EVENT_GFX_DIAMOND_CUSHION            172
#define OBJ_EVENT_GFX_BALL_CUSHION               173
#define OBJ_EVENT_GFX_GRASS_CUSHION              174
#define OBJ_EVENT_GFX_FIRE_CUSHION               175
#define OBJ_EVENT_GFX_WATER_CUSHION              176
#define OBJ_EVENT_GFX_BIG_ARCANINE_DOLL          177
#define OBJ_EVENT_GFX_BIG_KOMMO_O_DOLL           178
#define OBJ_EVENT_GFX_BIG_LAPRAS_DOLL            179
#define OBJ_EVENT_GFX_BIG_RAIKOU_DOLL            180
#define OBJ_EVENT_GFX_BIG_ENTEI_DOLL             181
#define OBJ_EVENT_GFX_BIG_SUICUNE_DOLL           182
#define OBJ_EVENT_GFX_BIG_GYARADOS_DOLL          183
#define OBJ_EVENT_GFX_BIG_HO_OH_DOLL             184
#define OBJ_EVENT_GFX_BIG_LUGIA_DOLL             185
#define OBJ_EVENT_GFX_BIG_RAICHU_DOLL            186
#define OBJ_EVENT_GFX_LATIAS                     187
#define OBJ_EVENT_GFX_LATIOS                     188
#define OBJ_EVENT_GFX_GAMEBOY_KID                189
#define OBJ_EVENT_GFX_CONTEST_JUDGE              190
#define OBJ_EVENT_GFX_BRENDAN_WATERING           191
#define OBJ_EVENT_GFX_MAY_WATERING               192
#define OBJ_EVENT_GFX_BRENDAN_DECORATING         193
#define OBJ_EVENT_GFX_MAY_DECORATING             194
#define OBJ_EVENT_GFX_MARA                       195 // 8th gym leader, leader of Team Chimera, Ares' Daughter
#define OBJ_EVENT_GFX_MAXIE                      196
#define OBJ_EVENT_GFX_KYOGRE_FRONT               197
#define OBJ_EVENT_GFX_GROUDON_FRONT              198
#define OBJ_EVENT_GFX_FOSSIL                     199
#define OBJ_EVENT_GFX_REGIROCK                   200
#define OBJ_EVENT_GFX_REGICE                     201
#define OBJ_EVENT_GFX_REGISTEEL                  202
#define OBJ_EVENT_GFX_SKITTY                     203
#define OBJ_EVENT_GFX_KECLEON                    204
#define OBJ_EVENT_GFX_KYOGRE_ASLEEP              205
#define OBJ_EVENT_GFX_GROUDON_ASLEEP             206
#define OBJ_EVENT_GFX_RAYQUAZA                   207
#define OBJ_EVENT_GFX_ZIGZAGOON_2                208
#define OBJ_EVENT_GFX_PIKACHU                    209
#define OBJ_EVENT_GFX_AZUMARILL                  210
#define OBJ_EVENT_GFX_WINGULL                    211
#define OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW      212
#define OBJ_EVENT_GFX_TUBER_M_SWIMMING           213
#define OBJ_EVENT_GFX_AZURILL                    214
#define OBJ_EVENT_GFX_MOM                        215
#define OBJ_EVENT_GFX_LINK_BRENDAN               216
#define OBJ_EVENT_GFX_LINK_MAY                   217
#define OBJ_EVENT_GFX_JUAN                       218
#define OBJ_EVENT_GFX_SCOTT                      219
#define OBJ_EVENT_GFX_POOCHYENA                  220
#define OBJ_EVENT_GFX_KYOGRE_SIDE                221
#define OBJ_EVENT_GFX_GROUDON_SIDE               222
#define OBJ_EVENT_GFX_MYSTERY_GIFT_MAN           223
#define OBJ_EVENT_GFX_TRICK_HOUSE_STATUE         224
#define OBJ_EVENT_GFX_KIRLIA                     225
#define OBJ_EVENT_GFX_DUSCLOPS                   226
#define OBJ_EVENT_GFX_UNION_ROOM_NURSE           227
#define OBJ_EVENT_GFX_SUDOWOODO                  228
#define OBJ_EVENT_GFX_MEW                        229
#define OBJ_EVENT_GFX_RED                        230
#define OBJ_EVENT_GFX_LEAF                       231
#define OBJ_EVENT_GFX_DEOXYS                     232
#define OBJ_EVENT_GFX_DEOXYS_TRIANGLE            233
#define OBJ_EVENT_GFX_BRANDON                    234
#define OBJ_EVENT_GFX_LINK_RS_BRENDAN            235
#define OBJ_EVENT_GFX_LINK_RS_MAY                236
#define OBJ_EVENT_GFX_LUGIA                      237
#define OBJ_EVENT_GFX_HOOH                       238
#define OBJ_EVENT_GFX_POKE_BALL                  239 // replaces ITEM_BALL
#define OBJ_EVENT_GFX_OW_MON                     240
#define OBJ_EVENT_GFX_LIGHT_SPRITE               OBJ_EVENT_GFX_QUINTY_PLUMP
#define OBJ_EVENT_GFX_PERFORMER_M                241
#define OBJ_EVENT_GFX_PUNK_ROCKER                242
#define OBJ_EVENT_GFX_OFFICER                    243
#define OBJ_EVENT_GFX_DIVER                      244
#define OBJ_EVENT_GFX_PIRAEUS                    245
#define OBJ_EVENT_GFX_CHIMERA_ADMIN_M            246
#define OBJ_EVENT_GFX_CHIMERA_ADMIN_F            247
#define OBJ_EVENT_GFX_WINDMILL_TL                248
#define OBJ_EVENT_GFX_WINDMILL_TR                249
#define OBJ_EVENT_GFX_WINDMILL_BL                250
#define OBJ_EVENT_GFX_WINDMILL_BR                251

// Outfit: Kalos Outfit (Calem & Serena)
#define OBJ_EVENT_GFX_OUTFIT_CALEM_NORMAL        252
#define OBJ_EVENT_GFX_OUTFIT_CALEM_MACH_BIKE     253
#define OBJ_EVENT_GFX_OUTFIT_CALEM_SURFING       254
#define OBJ_EVENT_GFX_OUTFIT_CALEM_FIELD_MOVE    255
#define OBJ_EVENT_GFX_OUTFIT_CALEM_ACRO_BIKE     256
#define OBJ_EVENT_GFX_OUTFIT_CALEM_UNDERWATER    257
#define OBJ_EVENT_GFX_OUTFIT_CALEM_FISHING       258
#define OBJ_EVENT_GFX_OUTFIT_CALEM_WATERING      259
#define OBJ_EVENT_GFX_OUTFIT_CALEM_DECORATING    260
#define OBJ_EVENT_GFX_OUTFIT_SERENA_NORMAL       261
#define OBJ_EVENT_GFX_OUTFIT_SERENA_MACH_BIKE    262
#define OBJ_EVENT_GFX_OUTFIT_SERENA_SURFING      263
#define OBJ_EVENT_GFX_OUTFIT_SERENA_FIELD_MOVE   264
#define OBJ_EVENT_GFX_OUTFIT_SERENA_ACRO_BIKE    265
#define OBJ_EVENT_GFX_OUTFIT_SERENA_UNDERWATER   266
#define OBJ_EVENT_GFX_OUTFIT_SERENA_FISHING      267
#define OBJ_EVENT_GFX_OUTFIT_SERENA_WATERING     268
#define OBJ_EVENT_GFX_OUTFIT_SERENA_DECORATING   269

// Outfit: Zookeeper M and F
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_M_NORMAL        270
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_M_MACH_BIKE     271
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_M_SURFING       272
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_M_FIELD_MOVE    273
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_M_ACRO_BIKE     274
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_M_UNDERWATER    275
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_M_FISHING       276
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_M_WATERING      277
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_M_DECORATING    278
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_F_NORMAL        279
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_F_MACH_BIKE     280
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_F_SURFING       281
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_F_FIELD_MOVE    282
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_F_ACRO_BIKE     283
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_F_UNDERWATER    284
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_F_FISHING       285
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_F_WATERING      286
#define OBJ_EVENT_GFX_OUTFIT_ZOOKEEPER_F_DECORATING    287

// Outfit: Traditional M and F
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_M_NORMAL        288
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_M_SURFING       289
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_M_FIELD_MOVE    290
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_M_ACRO_BIKE     291
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_M_UNDERWATER    292
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_M_FISHING       293
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_M_WATERING      294
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_M_DECORATING    295
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_F_NORMAL        296
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_F_SURFING       297
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_F_FIELD_MOVE    298
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_F_ACRO_BIKE     299
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_F_UNDERWATER    300
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_F_FISHING       301
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_F_WATERING      302
#define OBJ_EVENT_GFX_OUTFIT_TRADITIONAL_F_DECORATING    303

// Outfit: East_Blue M and F
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_M_NORMAL        304
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_M_SURFING       305
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_M_FIELD_MOVE    306
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_M_ACRO_BIKE     307
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_M_UNDERWATER    308
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_M_FISHING       309
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_M_WATERING      310
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_M_DECORATING    311
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_F_NORMAL        312
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_F_SURFING       313
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_F_FIELD_MOVE    314
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_F_ACRO_BIKE     315
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_F_UNDERWATER    316
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_F_FISHING       317
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_F_WATERING      318
#define OBJ_EVENT_GFX_OUTFIT_EAST_BLUE_F_DECORATING    319

// Outfit: Coral M and F
#define OBJ_EVENT_GFX_OUTFIT_CORAL_M_NORMAL        320
#define OBJ_EVENT_GFX_OUTFIT_CORAL_M_SURFING       321
#define OBJ_EVENT_GFX_OUTFIT_CORAL_M_FIELD_MOVE    322
#define OBJ_EVENT_GFX_OUTFIT_CORAL_M_ACRO_BIKE     323
#define OBJ_EVENT_GFX_OUTFIT_CORAL_M_UNDERWATER    324
#define OBJ_EVENT_GFX_OUTFIT_CORAL_M_FISHING       325
#define OBJ_EVENT_GFX_OUTFIT_CORAL_M_WATERING      326
#define OBJ_EVENT_GFX_OUTFIT_CORAL_M_DECORATING    327
#define OBJ_EVENT_GFX_OUTFIT_CORAL_F_NORMAL        328
#define OBJ_EVENT_GFX_OUTFIT_CORAL_F_SURFING       329
#define OBJ_EVENT_GFX_OUTFIT_CORAL_F_FIELD_MOVE    330
#define OBJ_EVENT_GFX_OUTFIT_CORAL_F_ACRO_BIKE     331
#define OBJ_EVENT_GFX_OUTFIT_CORAL_F_UNDERWATER    332
#define OBJ_EVENT_GFX_OUTFIT_CORAL_F_FISHING       333
#define OBJ_EVENT_GFX_OUTFIT_CORAL_F_WATERING      334
#define OBJ_EVENT_GFX_OUTFIT_CORAL_F_DECORATING    335

// Outfit: Tropics M and F
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_M_NORMAL        336
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_M_SURFING       337
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_M_FIELD_MOVE    338
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_M_ACRO_BIKE     339
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_M_UNDERWATER    340
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_M_FISHING       341
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_M_WATERING      342
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_M_DECORATING    343
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_F_NORMAL        344
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_F_SURFING       345
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_F_FIELD_MOVE    346
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_F_ACRO_BIKE     347
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_F_UNDERWATER    348
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_F_FISHING       349
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_F_WATERING      350
#define OBJ_EVENT_GFX_OUTFIT_TROPICS_F_DECORATING    351

// Outfit: Old_Sofos M and F
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_M_NORMAL        352
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_M_SURFING       353
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_M_FIELD_MOVE    354
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_M_ACRO_BIKE     355
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_M_UNDERWATER    356
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_M_FISHING       357
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_M_WATERING      358
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_M_DECORATING    359
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_F_NORMAL        360
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_F_SURFING       361
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_F_FIELD_MOVE    362
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_F_ACRO_BIKE     363
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_F_UNDERWATER    364
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_F_FISHING       365
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_F_WATERING      366
#define OBJ_EVENT_GFX_OUTFIT_OLD_SOFOS_F_DECORATING    367

// Outfit: Petal M and F
#define OBJ_EVENT_GFX_OUTFIT_PETAL_M_NORMAL        368
#define OBJ_EVENT_GFX_OUTFIT_PETAL_M_SURFING       369
#define OBJ_EVENT_GFX_OUTFIT_PETAL_M_FIELD_MOVE    370
#define OBJ_EVENT_GFX_OUTFIT_PETAL_M_ACRO_BIKE     371
#define OBJ_EVENT_GFX_OUTFIT_PETAL_M_UNDERWATER    372
#define OBJ_EVENT_GFX_OUTFIT_PETAL_M_FISHING       373
#define OBJ_EVENT_GFX_OUTFIT_PETAL_M_WATERING      374
#define OBJ_EVENT_GFX_OUTFIT_PETAL_M_DECORATING    375
#define OBJ_EVENT_GFX_OUTFIT_PETAL_F_NORMAL        376
#define OBJ_EVENT_GFX_OUTFIT_PETAL_F_SURFING       377
#define OBJ_EVENT_GFX_OUTFIT_PETAL_F_FIELD_MOVE    378
#define OBJ_EVENT_GFX_OUTFIT_PETAL_F_ACRO_BIKE     379
#define OBJ_EVENT_GFX_OUTFIT_PETAL_F_UNDERWATER    380
#define OBJ_EVENT_GFX_OUTFIT_PETAL_F_FISHING       381
#define OBJ_EVENT_GFX_OUTFIT_PETAL_F_WATERING      382
#define OBJ_EVENT_GFX_OUTFIT_PETAL_F_DECORATING    383

// Outfit: Palati M and F
#define OBJ_EVENT_GFX_OUTFIT_PALATI_M_NORMAL        384
#define OBJ_EVENT_GFX_OUTFIT_PALATI_M_SURFING       385
#define OBJ_EVENT_GFX_OUTFIT_PALATI_M_FIELD_MOVE    386
#define OBJ_EVENT_GFX_OUTFIT_PALATI_M_ACRO_BIKE     387
#define OBJ_EVENT_GFX_OUTFIT_PALATI_M_UNDERWATER    388
#define OBJ_EVENT_GFX_OUTFIT_PALATI_M_FISHING       389
#define OBJ_EVENT_GFX_OUTFIT_PALATI_M_WATERING      390
#define OBJ_EVENT_GFX_OUTFIT_PALATI_M_DECORATING    391
#define OBJ_EVENT_GFX_OUTFIT_PALATI_F_NORMAL        392
#define OBJ_EVENT_GFX_OUTFIT_PALATI_F_SURFING       393
#define OBJ_EVENT_GFX_OUTFIT_PALATI_F_FIELD_MOVE    394
#define OBJ_EVENT_GFX_OUTFIT_PALATI_F_ACRO_BIKE     395
#define OBJ_EVENT_GFX_OUTFIT_PALATI_F_UNDERWATER    396
#define OBJ_EVENT_GFX_OUTFIT_PALATI_F_FISHING       397
#define OBJ_EVENT_GFX_OUTFIT_PALATI_F_WATERING      398
#define OBJ_EVENT_GFX_OUTFIT_PALATI_F_DECORATING    399

// Outfit: Ancient M and F
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_M_NORMAL        400
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_M_SURFING       401
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_M_FIELD_MOVE    402
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_M_ACRO_BIKE     403
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_M_UNDERWATER    404
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_M_FISHING       405
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_M_WATERING      406
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_M_DECORATING    407
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_F_NORMAL        408
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_F_SURFING       409
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_F_FIELD_MOVE    410
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_F_ACRO_BIKE     411
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_F_UNDERWATER    412
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_F_FISHING       413
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_F_WATERING      414
#define OBJ_EVENT_GFX_OUTFIT_ANCIENT_F_DECORATING    415

// Outfit: Johto M and F
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_M_NORMAL        416
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_M_SURFING       417
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_M_FIELD_MOVE    418
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_M_ACRO_BIKE     419
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_M_UNDERWATER    420
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_M_FISHING       421
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_M_WATERING      422
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_M_DECORATING    423
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_F_NORMAL        424
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_F_SURFING       425
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_F_FIELD_MOVE    426
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_F_ACRO_BIKE     427
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_F_UNDERWATER    428
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_F_FISHING       429
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_F_WATERING      430
#define OBJ_EVENT_GFX_OUTFIT_JOHTO_F_DECORATING    431

// Outfit: Alola M and F
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_M_NORMAL        432
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_M_SURFING       433
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_M_FIELD_MOVE    434
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_M_ACRO_BIKE     435
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_M_UNDERWATER    436
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_M_FISHING       437
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_M_WATERING      438
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_M_DECORATING    439
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_F_NORMAL        440
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_F_SURFING       441
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_F_FIELD_MOVE    442
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_F_ACRO_BIKE     443
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_F_UNDERWATER    444
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_F_FISHING       445
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_F_WATERING      446
#define OBJ_EVENT_GFX_OUTFIT_ALOLA_F_DECORATING    447

// Outfit: Paldea M and F
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_M_NORMAL        448
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_M_SURFING       449
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_M_FIELD_MOVE    450
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_M_ACRO_BIKE     451
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_M_UNDERWATER    452
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_M_FISHING       453
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_M_WATERING      454
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_M_DECORATING    455
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_F_NORMAL        456
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_F_SURFING       457
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_F_FIELD_MOVE    458
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_F_ACRO_BIKE     459
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_F_UNDERWATER    460
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_F_FISHING       461
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_F_WATERING      462
#define OBJ_EVENT_GFX_OUTFIT_PALDEA_F_DECORATING    463

// Outfit: Hylian M and F
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_M_NORMAL        464
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_M_SURFING       465
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_M_FIELD_MOVE    466
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_M_ACRO_BIKE     467
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_M_UNDERWATER    468
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_M_FISHING       469
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_M_WATERING      470
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_M_DECORATING    471
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_F_NORMAL        472
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_F_SURFING       473
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_F_FIELD_MOVE    474
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_F_ACRO_BIKE     475
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_F_UNDERWATER    476
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_F_FISHING       477
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_F_WATERING      478
#define OBJ_EVENT_GFX_OUTFIT_HYLIAN_F_DECORATING    479

#define OBJ_EVENT_GFX_ITEM_BALL_UNDERWATER          480

#define OBJ_EVENT_GFX_TOUCANNON_DOLL                481
#define OBJ_EVENT_GFX_ORICORIO_DOLL                 482

// NOTE: The maximum amount of object events has been expanded from 255 to 65535.
// Since dynamic graphics ids still require at least 16 free values, the actual limit
// is 65519, but even considering follower Pokémon, this should be more than enough :)
#define NUM_OBJ_EVENT_GFX                        483


// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   (NUM_OBJ_EVENT_GFX + 1)
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0x0)
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 0xF)
#define OBJ_EVENT_GFX_LAST   OBJ_EVENT_GFX_VAR_F

#define OBJ_EVENT_GFX_MON_BASE  0x200 // 512
#define OBJ_EVENT_GFX_SPECIES_BITS 12 // This will need to be updated when NUM_SPECIES is > ~3.5k
#define OBJ_EVENT_GFX_SPECIES_MASK ((1 << OBJ_EVENT_GFX_SPECIES_BITS) - 1)

// Used to call a specific species' follower graphics. Useful for static encounters.
#define OBJ_EVENT_GFX_SPECIES(name)       (SPECIES_##name + OBJ_EVENT_GFX_MON_BASE)
#define OBJ_EVENT_GFX_SPECIES_SHINY(name) (SPECIES_##name + OBJ_EVENT_GFX_MON_BASE + SPECIES_SHINY_TAG)

#define OW_SPECIES(x) (((x)->graphicsId & OBJ_EVENT_GFX_SPECIES_MASK) - OBJ_EVENT_GFX_MON_BASE)
#define OW_FORM(x) ((x)->graphicsId >> OBJ_EVENT_GFX_SPECIES_BITS)

// Whether Object Event is an OW pokemon
#define IS_OW_MON_OBJ(obj) ((obj)->graphicsId >= OBJ_EVENT_GFX_MON_BASE)

#define SHADOW_SIZE_S       0
#define SHADOW_SIZE_M       1
#define SHADOW_SIZE_L       2
#define SHADOW_SIZE_NONE    3   // Originally SHADOW_SIZE_XL, which went unused due to shadowSize in ObjectEventGraphicsInfo being only 2 bits.

#define SHADOW_SIZE_XL_BATTLE_ONLY  SHADOW_SIZE_NONE    // Battle-only definition for XL shadow size.

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2
#define TRACKS_SLITHER    3
#define TRACKS_SPOT       4
#define TRACKS_BUG        5

#define FIRST_DECORATION_SPRITE_GFX OBJ_EVENT_GFX_MIMIKYU_DOLL

#define OBJ_KIND_NORMAL 0
#define OBJ_KIND_CLONE  255 // Exclusive to FRLG

// Special object event local ids
// Used for link player OWs in CreateLinkPlayerSprite
#define OBJ_EVENT_ID_DYNAMIC_BASE 0xF0

#define OBJ_EVENT_ID_PLAYER 0xFF
#define OBJ_EVENT_ID_CAMERA 0x7F
#define OBJ_EVENT_ID_FOLLOWER 0xFE

// Object event local ids referenced in C files
#define LOCALID_ROUTE111_PLAYER_FALLING 45
#define LOCALID_BIRTH_ISLAND_EXTERIOR_ROCK 1
#define LOCALID_FARAWAY_ISLAND_MEW 1
#define LOCALID_UNION_ROOM_PLAYER_4 2
#define LOCALID_UNION_ROOM_PLAYER_8 3
#define LOCALID_UNION_ROOM_PLAYER_7 4
#define LOCALID_UNION_ROOM_PLAYER_6 5
#define LOCALID_UNION_ROOM_PLAYER_5 6
#define LOCALID_UNION_ROOM_PLAYER_3 7
#define LOCALID_UNION_ROOM_PLAYER_2 8
#define LOCALID_UNION_ROOM_PLAYER_1 9
#define LOCALID_BATTLE_TOWER_LOBBY_REPORTER 5
#define LOCALID_TRUCK_BOX_TOP 1
#define LOCALID_TRUCK_BOX_BOTTOM_L 2
#define LOCALID_TRUCK_BOX_BOTTOM_R 3
#define LOCALID_OLDALE_MART_CLERK 1
#define LOCALID_LAVARIDGE_MART_CLERK 1
#define LOCALID_FALLARBOR_MART_CLERK 1
#define LOCALID_VERDANTURF_MART_CLERK 1
#define LOCALID_PETALBURG_MART_CLERK 1
#define LOCALID_SLATEPORT_MART_CLERK 1
#define LOCALID_MAUVILLE_MART_CLERK 1
#define LOCALID_RUSTBORO_MART_CLERK 1
#define LOCALID_FORTREE_MART_CLERK 1
#define LOCALID_MOSSDEEP_MART_CLERK 1
#define LOCALID_SOOTOPOLIS_MART_CLERK 1
#define LOCALID_BATTLE_FRONTIER_MART_CLERK 1
#define LOCALID_SLATEPORT_ENERGY_GURU 25

// Emotes for emote scripting macro
#define EMOTE_EXCLAM 0
#define EMOTE_QUESTION 1
#define EMOTE_HEART 3

// Moved from src/event_object_movement.c so that they're accesible from other files.
#define OBJ_EVENT_PAL_TAG_BRENDAN                 0x1100
#define OBJ_EVENT_PAL_TAG_BRENDAN_REFLECTION      0x1101
#define OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION       0x1102
#define OBJ_EVENT_PAL_TAG_NPC_1                   0x1103
#define OBJ_EVENT_PAL_TAG_NPC_2                   0x1104
#define OBJ_EVENT_PAL_TAG_NPC_3                   0x1105
#define OBJ_EVENT_PAL_TAG_NPC_4                   0x1106
#define OBJ_EVENT_PAL_TAG_NPC_1_REFLECTION        0x1107
#define OBJ_EVENT_PAL_TAG_NPC_2_REFLECTION        0x1108
#define OBJ_EVENT_PAL_TAG_NPC_3_REFLECTION        0x1109
#define OBJ_EVENT_PAL_TAG_NPC_4_REFLECTION        0x110A
#define OBJ_EVENT_PAL_TAG_QUINTY_PLUMP            0x110B
#define OBJ_EVENT_PAL_TAG_QUINTY_PLUMP_REFLECTION 0x110C
#define OBJ_EVENT_PAL_TAG_TRUCK                   0x110D
#define OBJ_EVENT_PAL_TAG_VIGOROTH                0x110E
#define OBJ_EVENT_PAL_TAG_ZIGZAGOON               0x110F
#define OBJ_EVENT_PAL_TAG_MAY                     0x1110
#define OBJ_EVENT_PAL_TAG_MAY_REFLECTION          0x1111
#define OBJ_EVENT_PAL_TAG_MOVING_BOX              0x1112
#define OBJ_EVENT_PAL_TAG_CABLE_CAR               0x1113
#define OBJ_EVENT_PAL_TAG_SSTIDAL                 0x1114
#define OBJ_EVENT_PAL_TAG_PLAYER_UNDERWATER       0x1115
#define OBJ_EVENT_PAL_TAG_KYOGRE                  0x1116
#define OBJ_EVENT_PAL_TAG_KYOGRE_REFLECTION       0x1117
#define OBJ_EVENT_PAL_TAG_GROUDON                 0x1118
#define OBJ_EVENT_PAL_TAG_GROUDON_REFLECTION      0x1119
#define OBJ_EVENT_PAL_TAG_UNUSED                  0x111A
#define OBJ_EVENT_PAL_TAG_SUBMARINE_SHADOW        0x111B
#define OBJ_EVENT_PAL_TAG_POOCHYENA               0x111C
#define OBJ_EVENT_PAL_TAG_RED_LEAF                0x111D
#define OBJ_EVENT_PAL_TAG_DEOXYS                  0x111E
#define OBJ_EVENT_PAL_TAG_BIRTH_ISLAND_STONE      0x111F
#define OBJ_EVENT_PAL_TAG_HO_OH                   0x1120
#define OBJ_EVENT_PAL_TAG_LUGIA                   0x1121
#define OBJ_EVENT_PAL_TAG_RS_BRENDAN              0x1122
#define OBJ_EVENT_PAL_TAG_RS_MAY                  0x1123
#define OBJ_EVENT_PAL_TAG_DYNAMIC                 0x1124
#define OBJ_EVENT_PAL_TAG_OUTFIT_KALOS            0x1125 // palette for Calem and Serena
#define OBJ_EVENT_PAL_TAG_OUTFIT_ZOOKEEPER        0x1126 // palette for Zookeeper M and F outfits
#define OBJ_EVENT_PAL_TAG_OUTFIT_TRADITIONAL      0x1127 // palette for traditional outfits
#define OBJ_EVENT_PAL_TAG_OUTFIT_EAST_BLUE        0x1128 // palette for east_blue outfits
#define OBJ_EVENT_PAL_TAG_OUTFIT_CORAL            0x1129 // palette for coral outfits
#define OBJ_EVENT_PAL_TAG_OUTFIT_TROPICS          0x1130 // palette for tropics outfits
#define OBJ_EVENT_PAL_TAG_OUTFIT_OLD_SOFOS        0x1131 // palette for old_sofos outfits
#define OBJ_EVENT_PAL_TAG_OUTFIT_PETAL            0x1132 // palette for petal outfits
#define OBJ_EVENT_PAL_TAG_OUTFIT_PALATI           0x1133 // palette for palati outfits
#define OBJ_EVENT_PAL_TAG_OUTFIT_ANCIENT          0x1134 // palette for ancient outfits
#define OBJ_EVENT_PAL_TAG_OUTFIT_JOHTO            0x1135 // palette for johto outfits
#define OBJ_EVENT_PAL_TAG_OUTFIT_ALOLA            0x1136 // palette for alola outfits
#define OBJ_EVENT_PAL_TAG_OUTFIT_PALDEA           0x1137 // palette for paldea outfits
#define OBJ_EVENT_PAL_TAG_OUTFIT_HYLIAN           0x1138 // palette for hylian outfits

#if OW_FOLLOWERS_POKEBALLS
// Vanilla
#define OBJ_EVENT_PAL_TAG_BALL_MASTER             0x1150
#define OBJ_EVENT_PAL_TAG_BALL_ULTRA              0x1151
#define OBJ_EVENT_PAL_TAG_BALL_GREAT              0x1152
#define OBJ_EVENT_PAL_TAG_BALL_SAFARI             0x1153
#define OBJ_EVENT_PAL_TAG_BALL_NET                0x1154
#define OBJ_EVENT_PAL_TAG_BALL_DIVE               0x1155
#define OBJ_EVENT_PAL_TAG_BALL_NEST               0x1156
#define OBJ_EVENT_PAL_TAG_BALL_REPEAT             0x1157
#define OBJ_EVENT_PAL_TAG_BALL_TIMER              0x1158
#define OBJ_EVENT_PAL_TAG_BALL_LUXURY             0x1159
#define OBJ_EVENT_PAL_TAG_BALL_PREMIER            0x115A
// Gen IV/Sinnoh
#define OBJ_EVENT_PAL_TAG_BALL_DUSK               0x115B
#define OBJ_EVENT_PAL_TAG_BALL_HEAL               0x115C
#define OBJ_EVENT_PAL_TAG_BALL_QUICK              0x115D
#define OBJ_EVENT_PAL_TAG_BALL_CHERISH            0x115E
#define OBJ_EVENT_PAL_TAG_BALL_PARK               0x115F
// Gen II/Johto Apricorns
#define OBJ_EVENT_PAL_TAG_BALL_FAST               0x1160
#define OBJ_EVENT_PAL_TAG_BALL_LEVEL              0x1161
#define OBJ_EVENT_PAL_TAG_BALL_LURE               0x1162
#define OBJ_EVENT_PAL_TAG_BALL_HEAVY              0x1163
#define OBJ_EVENT_PAL_TAG_BALL_LOVE               0x1164
#define OBJ_EVENT_PAL_TAG_BALL_FRIEND             0x1165
#define OBJ_EVENT_PAL_TAG_BALL_MOON               0x1166
#define OBJ_EVENT_PAL_TAG_BALL_SPORT              0x1167
// Gen V
#define OBJ_EVENT_PAL_TAG_BALL_DREAM              0x1168
// Gen VII
#define OBJ_EVENT_PAL_TAG_BALL_BEAST              0x1169
// Gen VIII
#define OBJ_EVENT_PAL_TAG_BALL_STRANGE            0x116A
#endif //OW_FOLLOWERS_POKEBALLS

#define OBJ_EVENT_PAL_TAG_WINDMILL                0x2001

#define OBJ_EVENT_PAL_TAG_BERRY_TREE_CHERI        0x18EC
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_CHESTO       0x18ED
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_PECHA        0x18EE
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_RAWST        0x18EF
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_ASPEAR       0x18F0
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_LEPPA        0x18F1
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_ORAN         0x18F2
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_PERSIM       0x18F3
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_LUM          0x18F4
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_SITRUS       0x18F5
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_CHILAN       0x18F6
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_OCCA         0x18F7
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_PASSHO       0x18F8
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_WACAN        0x18F9
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_RINDO        0x18FA
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_YACHE        0x18FB
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_CHOPLE       0x18FC
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_KEBIA        0x18FD
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_SHUCA        0x18FE
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_PAYAPA       0x18FF
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_TANGA        0x1900
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_CHARTI       0x1901
#define OBJ_EVENT_PAL_TAG_BERRY_TREE_KASIB        0x1902

// Used as a placeholder follower graphic
#define OBJ_EVENT_PAL_TAG_SUBSTITUTE              0x7611
#define OBJ_EVENT_PAL_TAG_LIGHT                   0x8001
#define OBJ_EVENT_PAL_TAG_LIGHT_2                 0x8002
#define OBJ_EVENT_PAL_TAG_EMOTES                  0x8003
#define OBJ_EVENT_PAL_TAG_NEON_LIGHT              0x8004
// Not a real OW palette tag; used for the white flash applied to followers
#define OBJ_EVENT_PAL_TAG_WHITE                   (OBJ_EVENT_PAL_TAG_NONE - 1)
#define OBJ_EVENT_PAL_TAG_NONE                    0x11FF

// This + localId is used as the tileTag
// for compressed graphicsInfos
// '(C)ompressed (E)vent'
#define COMP_OW_TILE_TAG_BASE 0xCE00

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
