#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

//Add your mugshot constants here
#define MUGSHOT_BRENDAN  0
#define MUGSHOT_MAY  1
#define MUGSHOT_TWIN  2  // ex: girl who warns you Birch is being attacked in Littleroot
#define MUGSHOT_BIRCH  3
#define MUGSHOT_WALLY  4
#define MUGSHOT_NURSEJOY  5
#define MUGSHOT_ROXANNE  6
#define MUGSHOT_BRAWLY  7
#define MUGSHOT_WATTSON  8
#define MUGSHOT_FLANNERY  9
#define MUGSHOT_NORMAN  10
#define MUGSHOT_WINONA  11
#define MUGSHOT_TATEANDLIZA  12
#define MUGSHOT_JUAN  13
#define MUGSHOT_WALLACE  14
#define MUGSHOT_SIDNEY  15
#define MUGSHOT_PHOEBE  16
#define MUGSHOT_GLACIA  17
#define MUGSHOT_DRAKE  18
#define MUGSHOT_STEVEN  19
#define MUGSHOT_AQUAGRUNTM  20
#define MUGSHOT_AQUAGRUNTF  21
#define MUGSHOT_MAGMAGRUNTM  22
#define MUGSHOT_MAGMAGRUNTF  23
#define MUGSHOT_ARCHIE  24
#define MUGSHOT_MAXIE  25
#define MUGSHOT_YOUNGSTER  26
#define MUGSHOT_BEAUTY  27
#define MUGSHOT_BLACKBELT  28
#define MUGSHOT_BOY1  29
#define MUGSHOT_BOY2  30
#define MUGSHOT_BOY3  31
#define MUGSHOT_BUG_CATCHER  32
#define MUGSHOT_CAMPER  33
#define MUGSHOT_DEVONEMPLOYEE  34
#define MUGSHOT_EXPERTF  35
#define MUGSHOT_EXPERTM  36
#define MUGSHOT_BRINEY  37 // ALSO USED FOR OBJ_EVENT_GFX_OLD_MAN
#define MUGSHOT_FATMAN  38
#define MUGSHOT_FISHERMAN  39
#define MUGSHOT_GENTLEMAN  40
#define MUGSHOT_GIRL1  41
#define MUGSHOT_GIRL2  42
#define MUGSHOT_GIRL3  43
#define MUGSHOT_HEXMANIAC  44
#define MUGSHOT_HIKER  45
#define MUGSHOT_LASS  46
#define MUGSHOT_LITTLEBOY  47
#define MUGSHOT_LITTLEGIRL  48
#define MUGSHOT_MAN1  49
#define MUGSHOT_MAN2  50
#define MUGSHOT_MAN3  51
#define MUGSHOT_MAN4  52
#define MUGSHOT_MAN5  53
#define MUGSHOT_MANIAC  54
#define MUGSHOT_MOM  55
#define MUGSHOT_NINJABOY  56
#define MUGSHOT_OLDWOMAN  57
#define MUGSHOT_PICNICKER  58
#define MUGSHOT_POKEFANF  59
#define MUGSHOT_POKEFANM  60
#define MUGSHOT_PSYCHICM  61

#endif