#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

//Add your mugshot constants here
#define MUGSHOT_BRENDAN  0
#define MUGSHOT_MAY  1
#define MUGSHOT_TWIN  2  // ex: girl who warns you Birch is being attacked in Littleroot
#define MUGSHOT_BIRCH  3
#define MUGSHOT_WALLY  4
#define MUGSHOT_NURSEJOY  5
#define MUGSHOT_ROXANNE  6
#define MUGSHOT_BRAWLY  7
#define MUGSHOT_WATTSON  8
#define MUGSHOT_FLANNERY  9
#define MUGSHOT_NORMAN  10
#define MUGSHOT_WINONA  11
#define MUGSHOT_TATEANDLIZA  12
#define MUGSHOT_JUAN  13
#define MUGSHOT_WALLACE  14
#define MUGSHOT_SIDNEY  15
#define MUGSHOT_PHOEBE  16
#define MUGSHOT_GLACIA  17
#define MUGSHOT_DRAKE  18
#define MUGSHOT_STEVEN  19
#define MUGSHOT_AQUAGRUNTM  20
#define MUGSHOT_AQUAGRUNTF  21
#define MUGSHOT_MAGMAGRUNTM  22
#define MUGSHOT_MAGMAGRUNTF  23
#define MUGSHOT_ARCHIE  24
#define MUGSHOT_MAXIE  25

#endif