#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                          0
#define TRAINER_BRONZE_PASS_CHIMERA_GRUNT     1 // chimera grunt
#define TRAINER_EMERICK_BRONZEFIELDS          2
#define TRAINER_JOSEPH_BRONZEFIELDS          3
#define TRAINER_WYATT_BRONZEFIELDS          4
#define TRAINER_MILON_BRONZEFIELDS          5
#define TRAINER_KALL_BRONZEFIELDS       6
#define TRAINER_THERSON_BRONZEFIELDS       7
#define TRAINER_LEADER_POLYMNIA       8
#define TRAINER_JUSMAILGYM_KARI                   9
#define TRAINER_JUSMAILGYM_IASON        10
#define TRAINER_JUSMAILGYM_BRYCE                       11
#define TRAINER_JUSMAILGYM_ADEL                      12
#define TRAINER_ED                           13
#define TRAINER_JUSMAIL_RANIA      14
#define TRAINER_LEADER_POLYMNIA_HARD                       15
#define TRAINER_ACRISIAMTNS_TYRE         16
#define TRAINER_ACRISIAMTNS_ELISSA         17
#define TRAINER_RIVERWALK_TRAIL_W_JOSUA         18
#define TRAINER_ACRISIAMTNS_ULF         19
#define TRAINER_ACRISIAMTNS_JAMMA               20
#define TRAINER_ACRISIAMTNS_GREG               21
#define TRAINER_ACRISIAMTNS_HUGH         22
#define TRAINER_ACRISIACAVES_F1_LANA              23
#define TRAINER_ACRISIACAVES_F1_FRAIA              24
#define TRAINER_RIVERWALK_TRAIL_W_UMBER              25
#define TRAINER_RIVERWALK_TRAIL_S_BERKLEY         26
#define TRAINER_RIVERWALK_TRAIL_W_MARGAREY         27
#define TRAINER_RIVERWALK_TRAIL_W_KYLON         28
#define TRAINER_LEADER_OURANI                     29
#define TRAINER_LEADER_OURANI_HARD                         30
#define TRAINER_WANDERERSWOODS_ZANDER                       31
#define TRAINER_WANDERERSWOODS_KALLAS     32
#define TRAINER_WANDERERSWOODS_MARTHA       33
#define TRAINER_WANDERERSWOODS_ALEXI                       34
#define TRAINER_WANDERERSWOODS_ELLIE                         35
#define TRAINER_WANDERERSWOODS_CHIMERA_ADMIN                        36
#define TRAINER_BRONZEPASS_ROSE              37 // Lass in BronzePass_North
#define TRAINER_BRONZEPASS_FELIX             38 // Boy in BronzePass_North
#define TRAINER_WANDERERSWOODS_CHIMERA_ADMIN_HARD                       39
#define TRAINER_WANDERERSWOODS_LYDIA                       40
#define TRAINER_WANDERERSWOODS_THOMAS                       41
#define TRAINER_PYTHIOSGYM_ROSARA                       42
#define TRAINER_PYTHIOSGYM_TAFOS                       43
#define TRAINER_PYTHIOSGYM_ADDONIS                      44
#define TRAINER_BRONZEPASS_CHIP              45 // Bug Catcher in BronzePass_North
#define TRAINER_PYTHIOSGYM_GERONI                       46
#define TRAINER_PYTHIOSGYM_YANNA                      47
#define TRAINER_LEADER_KLEIO                      48
#define TRAINER_LEADER_KLEIO_HARD                      49
#define TRAINER_ERINYSPATH_CHIMERA_ADMIN                      50
#define TRAINER_ERINYSPATH_CHIMERA_ADMIN_HARD               51
#define TRAINER_PYTHIOSCEMETERY_CHIMERA_GRUNT_1               52
#define TRAINER_PYTHIOSCEMETERY_CHIMERA_GRUNT_2               53
#define TRAINER_PYTHIOSCEMETERY_CHIMERA_GRUNT_3               54
#define TRAINER_PYTHIOSCEMETERY_MARIA               55
#define TRAINER_PYTHIOSCEMETERY_ARKOS               56
#define TRAINER_PYTHIOSCEMETERY_GALEI                       57
#define TRAINER_RIVERWALK_TRAIL_S_MARKUS                      58
#define TRAINER_RIVERWALK_TRAIL_S_TINA                         59
#define TRAINER_RIVERWALK_TRAIL_S_GIANNA                       60
#define TRAINER_RIVERWALK_TRAIL_S_BARNETT                       61
#define TRAINER_KALAMI_GYM_REX                       62
#define TRAINER_KALAMI_GYM_DANIEL                       63
#define TRAINER_KALAMI_GYM_TASOULA                      64
#define TRAINER_ERINYSPATH_E_LUEROI                        65
#define TRAINER_ERINYSPATH_E_KAYLEY                      66
#define TRAINER_ERINYSPATH_E_ROGER                      67
#define TRAINER_ERINYSPATH_W_HELENA                      68
#define TRAINER_ERINYSPATH_W_LEWEY                      69
#define TRAINER_ERINYSPATH_W_IRO_AND_ANNA                      70
#define TRAINER_ERINYSPATH_W_DAMON                      71
#define TRAINER_ERINYSPATH_W_TISIAS                       72
#define TRAINER_FROSLASSCAVERN_F1_ROBIN                       73
#define TRAINER_FROSLASSCAVERN_F1_CARMIN                        74
#define TRAINER_FROSLASSCAVERN_F1_ENTO                      75
#define TRAINER_FROSLASSCAVERN_F2_SANDOR                      76
#define TRAINER_FROSLASSCAVERN_F3_BEATRICE                        77
#define TRAINER_FROSLASSCAVERN_F3_KAUROS                     78
#define TRAINER_FROSLASSCAVERN_F3_MAXILLA                        79
#define TRAINER_ASFALHILLS_SALMAI                       80
#define TRAINER_ASFALHILLS_ARDRIN                       81
#define TRAINER_ASFALHILLS_VITO                         82
#define TRAINER_WANDERERSWOODS_S_YAMIR                         83
#define TRAINER_WANDERERSWOODS_S_WARREN                     84
#define TRAINER_WANDERERSWOODS_S_DUNCAN                     85
#define TRAINER_WANDERERSWOODS_S_DONNA                     86
#define TRAINER_ASFALHILLS_LENA_AND_MARISA                     87
#define TRAINER_ASFALHILLS_ARISBE                       88
#define TRAINER_ASFALHILLS_PROTHOE                         89
#define TRAINER_ASFALHILLS_BATTO                       90
#define TRAINER_SOFOS_CITY_CHIMERA_GRUNT                         91
#define TRAINER_SATYRSLAIR_CHIMERA_GRUNT_1                        92
#define TRAINER_SATYRSLAIR_CHIMERA_GRUNT_2                        93
#define TRAINER_SOFOSGYM_BROOKE                     94 // 0x55E i think
#define TRAINER_SOFOSGYM_TYRIEN                     95
#define TRAINER_SOFOSGYM_SAPPHA                         96
#define TRAINER_SOFOSGYM_ARISTO                      97
#define TRAINER_LEADER_TERPSIKORE                     98
#define TRAINER_LEADER_TERPSIKORE_HARD                     99
#define TRAINER_ASTERISEA_AESON                       100
#define TRAINER_ASTERISEA_TALEIA                    101
#define TRAINER_ASTERISEA_HAMON                    102
#define TRAINER_ASTERISEA_GEORGIA                    103
#define TRAINER_ASTERISEA_TRYFON                    104
#define TRAINER_ASTERISEA_WILLY                    105
#define TRAINER_ASTERISEA_CELINA                      106
#define TRAINER_ASTERISEA_KIDA                       107
#define TRAINER_ASTERISEA_SIKAR                   108
#define TRAINER_ASTERISEA_HAMMON                       109
#define TRAINER_ASTERISEA_MATILDA                   110
#define TRAINER_ASTERISEA_HARVEY                   111
#define TRAINER_ASTERISEA_JOSEPH                   112
#define TRAINER_ASTERISEA_LEON                   113
#define TRAINER_ASTERISEA_MAURIE                     114
#define TRAINER_ASTERISEA_SERGIUS                      115
#define TRAINER_ASTERISEA_SILVIA        116
#define TRAINER_ASTERISEA_IRENE                     117
#define TRAINER_ASTERISEA_HONORIA                     118
#define TRAINER_MYRRINIGYM_HAILEY                       119
#define TRAINER_MYRRINIGYM_TASOS                     120
#define TRAINER_MYRRINIGYM_REMIGIO                     121
#define TRAINER_MYRRINIGYM_ALMA                     122
#define TRAINER_LEADER_EUTERPE                     123
#define TRAINER_LEADER_EUTERPE_HARD                     124
#define TRAINER_MARMAROMINES_GRUNT_1                      125
#define TRAINER_MARMAROMINES_GRUNT_2                     126
#define TRAINER_MARMAROMINES_CHIMERA_ADMIN                   127
#define TRAINER_MARMAROMINES_CHIMERA_ADMIN_HARD                      128
#define TRAINER_UNDERWATER_JAN                     129
#define TRAINER_UNDERWATER_PANAU                      130
#define TRAINER_UNDERWATER_YARIKH                     131
#define TRAINER_UNDERWATER_WESTON                   132
#define TRAINER_UNDERWATER_MAURICIUS                   133
#define TRAINER_UNDERWATER_QUINTUS                   134
#define TRAINER_UNDERWATER_ARIK                   135
#define TRAINER_PENTEPETAL_CHIMERA_GRUNT                   136
#define TRAINER_VULCAISEA_FREDDY                      137
#define TRAINER_VULCAISEA_SABRINA                      138
#define TRAINER_VULCAISEA_SHERRY                   139
#define TRAINER_VULCAISEA_LUSIO                   140
#define TRAINER_VULCAISEA_MAHYA                   141
#define TRAINER_VULCAISEA_LEYLI                   142
#define TRAINER_VULCAISEA_ZISSIS                     143
#define TRAINER_VULCAISEA_PELAGIA                    144
#define TRAINER_VULCAISEA_JAXON                        145
#define TRAINER_VULCAISEA_VICTORIA          146
#define TRAINER_VULCAISEA_JULIEN                     147
#define TRAINER_VULCAISEA_TABATA                     148
#define TRAINER_VULCAISEA_SEBASTIAN                     149
#define TRAINER_FRESCOISLES_STELLA                     150
#define TRAINER_FRESCOGYM_GIDEON                        151
#define TRAINER_FRESCOGYM_MELODY                     152
#define TRAINER_FRESCOGYM_MAISIE                     153
#define TRAINER_FRESCOGYM_AZIZ                      154
#define TRAINER_FRESCOGYM_FRIDA                      155
#define TRAINER_LEADER_THALIAANDMELPOMENE                      156
#define TRAINER_LEADER_THALIAANDMELPOMENE_HARD                     157
#define TRAINER_KAPTARAISLAND_YESUI                       158
#define TRAINER_KAPTARAISLAND_ISSA                     159
#define TRAINER_KAPTARAISLAND_GRIGOR                      160
#define TRAINER_KAPTARAISLAND_MANTO                       161
#define TRAINER_KAPTARAISLAND_STAN                        162
#define TRAINER_KAPTARAISLAND_HORATIO                       163
#define TRAINER_KAPTARAISLAND_EDITH                        164
#define TRAINER_KAPTARAISLAND_FLYGUY                      165
#define TRAINER_KAPTARAISLAND_JON_AND_ROSE                     166
#define TRAINER_PALATIGYM_MUKHIN                      167
#define TRAINER_PALATIGYM_RAIMUND                    168
#define TRAINER_PALATIGYM_MELINA                     169
#define TRAINER_PALATIGYM_JULIE                    170
#define TRAINER_PALATIGYM_COLETTE                       171
#define TRAINER_JACK                        172
#define TRAINER_LEADER_RHADINE                      173
#define TRAINER_LEADER_RHADINE_HARD                        174
#define TRAINER_KAPTARAWEST_DANI                      175
#define TRAINER_KAPTARAWEST_BARREL                      176
#define TRAINER_KAPTARAWEST_SALLADOR                      177
#define TRAINER_KAPTARAWEST_PENNY                      178
#define TRAINER_KAPTARAWEST_ALLAN                       179
#define TRAINER_KAPTARAWEST_CHIMERA_ADMIN                     180
#define TRAINER_KAPTARAWEST_CHIMERA_ADMIN_HARD                        181
#define TRAINER_SATYRSLAIR_CHIMERA_ADMIN                      182
#define TRAINER_SATYRSLAIR_CHIMERA_ADMIN_HARD                       183
#define TRAINER_LASTLIGHT_HARLEY                       184
#define TRAINER_LASTLIGHT_BILLIE                       185
#define TRAINER_LASTLIGHT_ZOEY                       186
#define TRAINER_LASTLIGHT_PHALLON                       187
#define TRAINER_LASTLIGHT_NIKITAS                        188
#define TRAINER_LASTLIGHT_LOUKAS                     189
#define TRAINER_DIOXIPPUS_KALLIOPE                     190
#define TRAINER_DIOXIPPUS_KALLIOPE_HARD                        191
#define TRAINER_CORRINCROSSING_WYATT        192
#define TRAINER_CORRINCROSSING_JUNIOR        193
#define TRAINER_CORRINCROSSING_VASIA                       194
#define TRAINER_CORRINCROSSING_ALFRED                  195
#define TRAINER_CORRINCROSSING_DARCEY                    196
#define TRAINER_CORRINCROSSING_MAXIM                    197
#define TRAINER_CORRINCROSSING_OSKAR                    198
#define TRAINER_PORTPELLO_RANIA                    199
#define TRAINER_PORTPELLO_RANIA_HARD                    200
#define TRAINER_NYXTRAILS_HARRY                        201
#define TRAINER_NYXTRAILS_BRIENNE                        202
#define TRAINER_NYXTRAILS_SAMWELL                        203
#define TRAINER_NYXTRAILS_ADRIA                        204
#define TRAINER_NYXTRAILS_GRUNT1                      205
#define TRAINER_NYXTRAILS_GRUNT2                    206
#define TRAINER_NYXTRAILS_GRUNT3                    207
#define TRAINER_NYXTRAILS_GRUNT4                    208
#define TRAINER_NYXTRAILS_GRUNT5                    209
#define TRAINER_NYXTRAILS_GRUNT6                    210
#define TRAINER_AREIOS_CHIMERA_ADMIN_F                        211
#define TRAINER_AREIOS_CHIMERA_ADMIN_M                        212
#define TRAINER_NYXTRAILS_GRUNT7                       213
#define TRAINER_LEADER_KALLIOPE                       214
#define TRAINER_LEADER_KALLIOPE_HARD                      215
#define TRAINER_PENTEPETAL_RANIA                     216
#define TRAINER_PALATI_RANIA                      217
#define TRAINER_ASFALHILLS_NIKO                      218
#define TRAINER_POLLENROAD_RUBEN                     219
#define TRAINER_POLLENROAD_JONAH                     220
#define TRAINER_POLLENROAD_HANNAH                     221
#define TRAINER_POLLENROAD_ASHARI                     222
#define TRAINER_POLLENROAD_MARTIN                       223
#define TRAINER_POLLENROAD_VIKTOR                      224
#define TRAINER_POLLENROAD_ALICIA                      225
#define TRAINER_DAVOSISTRAITS_NEWELL                   226
#define TRAINER_DAVOSISTRAITS_LEAH                       227
#define TRAINER_DAVOSISTRAITS_ALKIS                   228
#define TRAINER_DAVOSISTRAITS_LEONIDAS                   229
#define TRAINER_DAVOSISTRAITS_PATELINA                   230
#define TRAINER_DAVOSISTRAITS_MINAS                   231
#define TRAINER_DAVOSISTRAITS_RANIA                      232
#define TRAINER_DAVOSISTRAITS_RANIA_HARD                     233
#define TRAINER_ELITEFOUR_POLYMNIA                      234
#define TRAINER_ELITEFOUR_POLYMNIA_HARD                       235
#define TRAINER_DAVOSISTRAITS_THEO                     236
#define TRAINER_ELITEFOUR_TERPSIKORE                      237
#define TRAINER_ELITEFOUR_TERPSIKORE_HARD                   238
#define TRAINER_ELITEFOUR_EUTERPE                   239
#define TRAINER_ELITEFOUR_EUTERPE_HARD                   240
#define TRAINER_ELITEFOUR_RHADINE                   241
#define TRAINER_ELITEFOUR_RHADINE_HARD                   242
#define TRAINER_ELITEFOUR_ANYALIOS                      243
#define TRAINER_ELITEFOUR_ANYALIOS_HARD                      244

// BELOW THIS: Wakewater Isle Trainers
#define TRAINER_WAKEWATER_SAMANTHA                    245
#define TRAINER_WAKEWATER_MAURA                       246
#define TRAINER_WAKEWATER_PIRAEUS                       247
#define TRAINER_WAKEWATER_LEXIE                      248
#define TRAINER_WAKEWATER_ALEXANDER                     249
#define TRAINER_WAKEWATER_KASSA                     250
#define TRAINER_WAKEWATER_POLYMNIA                     251
#define TRAINER_WAKEWATER_OURANI                     252
#define TRAINER_WAKEWATER_KLEIO                     253
#define TRAINER_WAKEWATER_TERPSIKORE                    254
#define TRAINER_WAKEWATER_EUTERPE                       255
#define TRAINER_WAKEWATER_THALIA_AND_MELPOMENE                      256
#define TRAINER_WAKEWATER_RHADINE                    257
#define TRAINER_WAKEWATER_KALLIOPE                    258
#define TRAINER_WAKEWATER_CHIMERA_ADMIN_M                    259
#define TRAINER_WAKEWATER_CHIMERA_ADMIN_F                    260
#define TRAINER_WAKEWATER_ANYALIOS                      261
#define TRAINER_WAKEWATER_RANIA                      262
#define TRAINER_WAKEWATER_MICHAH                      263
#define TRAINER_WAKEWATER_DRAKE                       264
#define TRAINER_WAKEWATER_SASHA                   265
#define TRAINER_WAKEWATER_CONNIE                    266
#define TRAINER_WAKEWATER_SHIA                   267
#define TRAINER_WAKEWATER_OLIVIA                  268
#define TRAINER_WAKEWATER_KYLE                    269
#define TRAINER_WAKEWATER_NEMO                    270
#define TRAINER_WAKEWATER_CASSIE             271
#define TRAINER_WAKEWATER_JARED                      272
#define TRAINER_WAKEWATER_CAIDEN                     273
#define TRAINER_WAKEWATER_SEBASTIAN                         274
#define TRAINER_WAKEWATER_BRODY                        275
#define TRAINER_WAKEWATER_JERRY                     276
#define TRAINER_WAKEWATER_ERIKOV                     277
#define TRAINER_WAKEWATER_RAJ                     278
#define TRAINER_WAKEWATER_BITA                     279
#define TRAINER_WAKEWATER_AMY                     280
#define TRAINER_WAKEWATER_GEORGIA                     281
#define TRAINER_WAKEWATER_NOB                     282
#define TRAINER_WAKEWATER_DALE                     283
#define TRAINER_WAKEWATER_ALLEN                     284
#define TRAINER_WAKEWATER_NIKITA                     285

#define TRAINER_SATYRSLAIR_MALU                286
#define TRAINER_SATYRSLAIR_RYAN              287
#define TRAINER_ANNA_AND_MEG_2              288
#define TRAINER_ANNA_AND_MEG_3              289
#define TRAINER_ANNA_AND_MEG_4              290
#define TRAINER_ANNA_AND_MEG_5              291
#define TRAINER_VICTOR                      292
#define TRAINER_WAKEWATER_MISSINGNOVGC                    293
#define TRAINER_WAKEWATER_SNAD                      294
#define TRAINER_MIGUEL_2                    295
#define TRAINER_MIGUEL_3                    296
#define TRAINER_MIGUEL_4                    297
#define TRAINER_MIGUEL_5                    298
#define TRAINER_VICTORIA                    299
#define TRAINER_VANESSA                     300
#define TRAINER_BETHANY                     301
#define TRAINER_ISABEL_1                    302
#define TRAINER_ISABEL_2                    303
#define TRAINER_ISABEL_3                    304
#define TRAINER_ISABEL_4                    305
#define TRAINER_ISABEL_5                    306
#define TRAINER_TIMOTHY_1                   307
#define TRAINER_TIMOTHY_2                   308
#define TRAINER_TIMOTHY_3                   309
#define TRAINER_TIMOTHY_4                   310
#define TRAINER_TIMOTHY_5                   311
#define TRAINER_VICKY                       312
#define TRAINER_SHELBY_1                    313
#define TRAINER_SHELBY_2                    314
#define TRAINER_SHELBY_3                    315
#define TRAINER_SHELBY_4                    316
#define TRAINER_SHELBY_5                    317
#define TRAINER_CALVIN_1                    318
#define TRAINER_BILLY                       319
#define TRAINER_JOSH                        320
#define TRAINER_TOMMY                       321
#define TRAINER_JOEY                        322
#define TRAINER_BEN                         323
#define TRAINER_QUINCY                      324
#define TRAINER_KATELYNN                    325
#define TRAINER_JAYLEN                      326
#define TRAINER_DILLON                      327
#define TRAINER_CALVIN_2                    328
#define TRAINER_CALVIN_3                    329
#define TRAINER_CALVIN_4                    330
#define TRAINER_CALVIN_5                    331
#define TRAINER_EDDIE                       332
#define TRAINER_ALLEN                       333
#define TRAINER_TIMMY                       334
#define TRAINER_WALLACE                     335
#define TRAINER_ANDREW                      336
#define TRAINER_IVAN                        337
#define TRAINER_CLAUDE                      338
#define TRAINER_ELLIOT_1                    339
#define TRAINER_NED                         340
#define TRAINER_DALE                        341
#define TRAINER_NOLAN                       342
#define TRAINER_BARNY                       343
#define TRAINER_WADE                        344
#define TRAINER_CARTER                      345
#define TRAINER_ELLIOT_2                    346
#define TRAINER_ELLIOT_3                    347
#define TRAINER_ELLIOT_4                    348
#define TRAINER_ELLIOT_5                    349
#define TRAINER_RONALD                      350
#define TRAINER_JACOB                       351
#define TRAINER_ANTHONY                     352
#define TRAINER_BENJAMIN_1                  353
#define TRAINER_BENJAMIN_2                  354
#define TRAINER_BENJAMIN_3                  355
#define TRAINER_BENJAMIN_4                  356
#define TRAINER_BENJAMIN_5                  357
#define TRAINER_ABIGAIL_1                   358
#define TRAINER_JASMINE                     359
#define TRAINER_ABIGAIL_2                   360
#define TRAINER_ABIGAIL_3                   361
#define TRAINER_ABIGAIL_4                   362
#define TRAINER_ABIGAIL_5                   363
#define TRAINER_DYLAN_1                     364
#define TRAINER_DYLAN_2                     365
#define TRAINER_DYLAN_3                     366
#define TRAINER_DYLAN_4                     367
#define TRAINER_DYLAN_5                     368
#define TRAINER_MARIA_1                     369
#define TRAINER_MARIA_2                     370
#define TRAINER_MARIA_3                     371
#define TRAINER_MARIA_4                     372
#define TRAINER_MARIA_5                     373
#define TRAINER_CAMDEN                      374
#define TRAINER_DEMETRIUS                   375
#define TRAINER_ISAIAH_1                    376
#define TRAINER_PABLO_1                     377
#define TRAINER_CHASE                       378
#define TRAINER_ISAIAH_2                    379
#define TRAINER_ISAIAH_3                    380
#define TRAINER_ISAIAH_4                    381
#define TRAINER_ISAIAH_5                    382
#define TRAINER_ISOBEL                      383
#define TRAINER_DONNY                       384
#define TRAINER_TALIA                       385
#define TRAINER_KATELYN_1                   386
#define TRAINER_ALLISON                     387
#define TRAINER_KATELYN_2                   388
#define TRAINER_KATELYN_3                   389
#define TRAINER_KATELYN_4                   390
#define TRAINER_KATELYN_5                   391
#define TRAINER_NICOLAS_1                   392
#define TRAINER_NICOLAS_2                   393
#define TRAINER_NICOLAS_3                   394
#define TRAINER_NICOLAS_4                   395
#define TRAINER_NICOLAS_5                   396
#define TRAINER_AARON                       397
#define TRAINER_PERRY                       398
#define TRAINER_HUGH                        399
#define TRAINER_PHIL                        400
#define TRAINER_JARED                       401
#define TRAINER_HUMBERTO                    402
#define TRAINER_PRESLEY                     403
#define TRAINER_DAVOSISTRAITS_RANIAO                     404
#define TRAINER_COLIN                       405
#define TRAINER_ROBERT_1                    406
#define TRAINER_BENNY                       407
#define TRAINER_CHESTER                     408
#define TRAINER_ROBERT_2                    409
#define TRAINER_ROBERT_3                    410
#define TRAINER_ROBERT_4                    411
#define TRAINER_ROBERT_5                    412
#define TRAINER_ALEX                        413
#define TRAINER_BECK                        414
#define TRAINER_YASU                        415
#define TRAINER_TAKASHI                     416
#define TRAINER_DIANNE                      417
#define TRAINER_JANI                        418
#define TRAINER_LAO_1                       419
#define TRAINER_LUNG                        420
#define TRAINER_LAO_2                       421
#define TRAINER_LAO_3                       422
#define TRAINER_LAO_4                       423
#define TRAINER_LAO_5                       424
#define TRAINER_JOCELYN                     425
#define TRAINER_LAURA                       426
#define TRAINER_CYNDY_1                     427
#define TRAINER_CORA                        428
#define TRAINER_WAKEWATER_BRODYA                       429
#define TRAINER_CYNDY_2                     430
#define TRAINER_CYNDY_3                     431
#define TRAINER_CYNDY_4                     432
#define TRAINER_CYNDY_5                     433
#define TRAINER_MADELINE_1                  434
#define TRAINER_CLARISSA                    435
#define TRAINER_ANGELICA                    436
#define TRAINER_MADELINE_2                  437
#define TRAINER_MADELINE_3                  438
#define TRAINER_MADELINE_4                  439
#define TRAINER_MADELINE_5                  440
#define TRAINER_BEVERLY                     441
#define TRAINER_IMANI                       442
#define TRAINER_KYLA                        443
#define TRAINER_DENISE                      444
#define TRAINER_BETH                        445
#define TRAINER_TARA                        446
#define TRAINER_MISSY                       447
#define TRAINER_ALICE                       448
#define TRAINER_JENNY_1                     449
#define TRAINER_GRACE                       450
#define TRAINER_TANYA                       451
#define TRAINER_SHARON                      452
#define TRAINER_NIKKI                       453
#define TRAINER_BRENDA                      454
#define TRAINER_KATIE                       455
#define TRAINER_SUSIE                       456
#define TRAINER_KARA                        457
#define TRAINER_DANA                        458
#define TRAINER_SIENNA                      459
#define TRAINER_DEBRA                       460
#define TRAINER_LINDA                       461
#define TRAINER_KAYLEE                      462
#define TRAINER_LAUREL                      463
#define TRAINER_CARLEE                      464
#define TRAINER_JENNY_2                     465
#define TRAINER_JENNY_3                     466
#define TRAINER_JENNY_4                     467
#define TRAINER_JENNY_5                     468
#define TRAINER_HEIDI                       469
#define TRAINER_BECKY                       470
#define TRAINER_CAROL                       471
#define TRAINER_NANCY                       472
#define TRAINER_MARTHA                      473
#define TRAINER_DIANA_1                     474
#define TRAINER_CEDRIC                      475
#define TRAINER_IRENE                       476
#define TRAINER_DIANA_2                     477
#define TRAINER_DIANA_3                     478
#define TRAINER_DIANA_4                     479
#define TRAINER_DIANA_5                     480
#define TRAINER_AMY_AND_LIV_1               481
#define TRAINER_AMY_AND_LIV_2               482
#define TRAINER_GINA_AND_MIA_1              483
#define TRAINER_MIU_AND_YUKI                484
#define TRAINER_AMY_AND_LIV_3               485
#define TRAINER_GINA_AND_MIA_2              486
#define TRAINER_AMY_AND_LIV_4               487
#define TRAINER_AMY_AND_LIV_5               488
#define TRAINER_AMY_AND_LIV_6               489
#define TRAINER_HUEY                        490
#define TRAINER_EDMOND                      491
#define TRAINER_ERNEST_1                    492
#define TRAINER_DWAYNE                      493
#define TRAINER_PHILLIP                     494
#define TRAINER_LEONARD                     495
#define TRAINER_DUNCAN                      496
#define TRAINER_ERNEST_2                    497
#define TRAINER_ERNEST_3                    498
#define TRAINER_ERNEST_4                    499
#define TRAINER_ERNEST_5                    500
#define TRAINER_ELI                         501
#define TRAINER_ANNIKA                      502
#define TRAINER_JAZMYN                      503
#define TRAINER_JONAS                       504
#define TRAINER_KAYLEY                      505
#define TRAINER_AURON                       506
#define TRAINER_KELVIN                      507
#define TRAINER_MARLEY                      508
#define TRAINER_REYNA                       509
#define TRAINER_HUDSON                      510
#define TRAINER_CONOR                       511
#define TRAINER_EDWIN_1                     512
#define TRAINER_HECTOR                      513
#define TRAINER_TABITHA_MOSSDEEP            514
#define TRAINER_EDWIN_2                     515
#define TRAINER_EDWIN_3                     516
#define TRAINER_EDWIN_4                     517
#define TRAINER_EDWIN_5                     518
#define TRAINER_WALLY_VR_1                  519
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    520
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    521
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    522
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   523
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   524
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   525
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   526
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   527
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   528
#define TRAINER_MAY_ROUTE_103_MUDKIP        529
#define TRAINER_MAY_ROUTE_110_MUDKIP        530
#define TRAINER_MAY_ROUTE_119_MUDKIP        531
#define TRAINER_MAY_ROUTE_103_TREECKO       532
#define TRAINER_MAY_ROUTE_110_TREECKO       533
#define TRAINER_MAY_ROUTE_119_TREECKO       534
#define TRAINER_MAY_ROUTE_103_TORCHIC       535
#define TRAINER_MAY_ROUTE_110_TORCHIC       536
#define TRAINER_MAY_ROUTE_119_TORCHIC       537
#define TRAINER_ISAAC_1                     538
#define TRAINER_DAVIS                       539
#define TRAINER_MITCHELL                    540
#define TRAINER_ISAAC_2                     541
#define TRAINER_ISAAC_3                     542
#define TRAINER_ISAAC_4                     543
#define TRAINER_ISAAC_5                     544
#define TRAINER_LYDIA_1                     545
#define TRAINER_HALLE                       546
#define TRAINER_GARRISON                    547
#define TRAINER_LYDIA_2                     548
#define TRAINER_LYDIA_3                     549
#define TRAINER_LYDIA_4                     550
#define TRAINER_LYDIA_5                     551
#define TRAINER_JACKSON_1                   552
#define TRAINER_LORENZO                     553
#define TRAINER_SEBASTIAN                   554
#define TRAINER_JACKSON_2                   555
#define TRAINER_JACKSON_3                   556
#define TRAINER_JACKSON_4                   557
#define TRAINER_JACKSON_5                   558
#define TRAINER_CATHERINE_1                 559
#define TRAINER_JENNA                       560
#define TRAINER_SOPHIA                      561
#define TRAINER_CATHERINE_2                 562
#define TRAINER_CATHERINE_3                 563
#define TRAINER_CATHERINE_4                 564
#define TRAINER_CATHERINE_5                 565
#define TRAINER_JULIO                       566
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     567
#define TRAINER_GRUNT_UNUSED                568
#define TRAINER_GRUNT_MT_PYRE_4             569
#define TRAINER_GRUNT_JAGGED_PASS           570
#define TRAINER_MARC                        571
#define TRAINER_BRENDEN                     572
#define TRAINER_LILITH                      573
#define TRAINER_CRISTIAN                    574
#define TRAINER_SYLVIA                      575
#define TRAINER_LEONARDO                    576
#define TRAINER_ATHENA                      577
#define TRAINER_HARRISON                    578
#define TRAINER_GRUNT_MT_CHIMNEY_2          579
#define TRAINER_CLARENCE                    580
#define TRAINER_TERRY                       581
#define TRAINER_NATE                        582
#define TRAINER_KATHLEEN                    583
#define TRAINER_CLIFFORD                    584
#define TRAINER_NICHOLAS                    585
#define TRAINER_GRUNT_SPACE_CENTER_3        586
#define TRAINER_GRUNT_SPACE_CENTER_4        587
#define TRAINER_GRUNT_SPACE_CENTER_5        588
#define TRAINER_GRUNT_SPACE_CENTER_6        589
#define TRAINER_GRUNT_SPACE_CENTER_7        590
#define TRAINER_MACEY                       591
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    592
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     593
#define TRAINER_PAXTON                      594
#define TRAINER_IKLEIO                    595
#define TRAINER_GRUNT_WEATHER_INST_5        596
#define TRAINER_TABITHA_MT_CHIMNEY          597
#define TRAINER_JONATHAN                    598
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    599
#define TRAINER_MAY_RUSTBORO_MUDKIP         600
#define TRAINER_MAXIE_MAGMA_HIDEOUT         601
#define TRAINER_MAXIE_MT_CHIMNEY            602
#define TRAINER_TIANA                       603
#define TRAINER_HALEY_1                     604
#define TRAINER_JANICE                      605
#define TRAINER_VIVI                        606
#define TRAINER_HALEY_2                     607
#define TRAINER_HALEY_3                     608
#define TRAINER_HALEY_4                     609
#define TRAINER_HALEY_5                     610
#define TRAINER_SALLY                       611
#define TRAINER_ROBIN                       612
#define TRAINER_ANDREA                      613
#define TRAINER_CRISSY                      614
#define TRAINER_RICK                        615
#define TRAINER_LYLE                        616
#define TRAINER_JOSE                        617
#define TRAINER_DOUG                        618
#define TRAINER_GREG                        619
#define TRAINER_KENT                        620
#define TRAINER_JAMES_1                     621
#define TRAINER_JAMES_2                     622
#define TRAINER_JAMES_3                     623
#define TRAINER_JAMES_4                     624
#define TRAINER_JAMES_5                     625
#define TRAINER_BRICE                       626
#define TRAINER_TRENT_1                     627
#define TRAINER_LENNY                       628
#define TRAINER_LUCAS_1                     629
#define TRAINER_ALAN                        630
#define TRAINER_CLARK                       631
#define TRAINER_ERIC                        632
#define TRAINER_LUCAS_2                     633
#define TRAINER_MIKE_1                      634
#define TRAINER_MIKE_2                      635
#define TRAINER_TRENT_2                     636
#define TRAINER_TRENT_3                     637
#define TRAINER_TRENT_4                     638
#define TRAINER_TRENT_5                     639
#define TRAINER_DEZ_AND_LUKE                640
#define TRAINER_LEA_AND_JED                 641
#define TRAINER_KIRA_AND_DAN_1              642
#define TRAINER_KIRA_AND_DAN_2              643
#define TRAINER_KIRA_AND_DAN_3              644
#define TRAINER_KIRA_AND_DAN_4              645
#define TRAINER_KIRA_AND_DAN_5              646
#define TRAINER_JOHANNA                     647
#define TRAINER_GERALD                      648
#define TRAINER_VIVIAN                      649
#define TRAINER_DANIELLE                    650
#define TRAINER_HIDEO                       651
#define TRAINER_KEIGO                       652
#define TRAINER_RILEY                       653
#define TRAINER_FLINT                       654
#define TRAINER_ASHLEY                      655
#define TRAINER_WALLY_MAUVILLE              656
#define TRAINER_WALLY_VR_2                  657
#define TRAINER_WALLY_VR_3                  658
#define TRAINER_WALLY_VR_4                  659
#define TRAINER_WALLY_VR_5                  660
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     661
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    662
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    663
#define TRAINER_MAY_LILYCOVE_MUDKIP         664
#define TRAINER_MAY_LILYCOVE_TREECKO        665
#define TRAINER_MAY_LILYCOVE_TORCHIC        666
#define TRAINER_JONAH                       667
#define TRAINER_HENRY                       668
#define TRAINER_ROGER                       669
#define TRAINER_ALEXA                       670
#define TRAINER_RUBEN                       671
#define TRAINER_KOJI_1                      672
#define TRAINER_WAYNE                       673
#define TRAINER_AIDAN                       674
#define TRAINER_REED                        675
#define TRAINER_TISHA                       676
#define TRAINER_TORI_AND_TIA                677
#define TRAINER_KIM_AND_IRIS                678
#define TRAINER_TYRA_AND_IVY                679
#define TRAINER_MEL_AND_PAUL                680
#define TRAINER_JOHN_AND_JAY_1              681
#define TRAINER_JOHN_AND_JAY_2              682
#define TRAINER_JOHN_AND_JAY_3              683
#define TRAINER_JOHN_AND_JAY_4              684
#define TRAINER_JOHN_AND_JAY_5              685
#define TRAINER_RELI_AND_IAN                686
#define TRAINER_LILA_AND_ROY_1              687
#define TRAINER_LILA_AND_ROY_2              688
#define TRAINER_LILA_AND_ROY_3              689
#define TRAINER_LILA_AND_ROY_4              690
#define TRAINER_LILA_AND_ROY_5              691
#define TRAINER_LISA_AND_RAY                692
#define TRAINER_CHRIS                       693
#define TRAINER_DAWSON                      694
#define TRAINER_SARAH                       695
#define TRAINER_DARIAN                      696
#define TRAINER_HAILEY                      697
#define TRAINER_CHANDLER                    698
#define TRAINER_KALEB                       699
#define TRAINER_JOSEPH                      700
#define TRAINER_ALYSSA                      701
#define TRAINER_MARCOS                      702
#define TRAINER_RHETT                       703
#define TRAINER_TYRON                       704
#define TRAINER_CELINA                      705
#define TRAINER_BIANCA                      706
#define TRAINER_HAYDEN                      707
#define TRAINER_SOPHIE                      708
#define TRAINER_COBY                        709
#define TRAINER_LAWRENCE                    710
#define TRAINER_WYATT                       711
#define TRAINER_ANGELINA                    712
#define TRAINER_KAI                         713
#define TRAINER_CHARLOTTE                   714
#define TRAINER_KAPTARAISLAND_EDITHDRE                     715
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       716
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       717
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       718
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       719
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       720
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       721
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       722
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       723
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       724
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      725
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      726
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      727
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      728
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      729
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      730
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      731
#define TRAINER_TABITHA_MAGMA_HIDEOUT       732
#define TRAINER_DARCY                       733
#define TRAINER_MAXIE_MOSSDEEP              734
#define TRAINER_PETE                        735
#define TRAINER_ISABELLE                    736
#define TRAINER_ANDRES_1                    737
#define TRAINER_JOSUE                       738
#define TRAINER_CAMRON                      739
#define TRAINER_CORY_1                      740
#define TRAINER_CAROLINA                    741
#define TRAINER_ELIJAH                      742
#define TRAINER_CELIA                       743
#define TRAINER_BRYAN                       744
#define TRAINER_BRANDEN                     745
#define TRAINER_BRYANT                      746
#define TRAINER_SHAYLA                      747
#define TRAINER_KYRA                        748
#define TRAINER_JAIDEN                      749
#define TRAINER_ALIX                        750
#define TRAINER_HELENE                      751
#define TRAINER_MARLENE                     752
#define TRAINER_DEVAN                       753
#define TRAINER_JOHNSON                     754
#define TRAINER_MELINA                      755
#define TRAINER_BRANDI                      756
#define TRAINER_AISHA                       757
#define TRAINER_MAKAYLA                     758
#define TRAINER_FABIAN                      759
#define TRAINER_DAYTON                      760
#define TRAINER_RACHEL                      761
#define TRAINER_LEONEL                      762
#define TRAINER_CALLIE                      763
#define TRAINER_CALE                        764
#define TRAINER_MYLES                       765
#define TRAINER_PAT                         766
#define TRAINER_CRISTIN_1                   767
#define TRAINER_MAY_RUSTBORO_TREECKO        768
#define TRAINER_MAY_RUSTBORO_TORCHIC        769
#define TRAINER_ROXANNE_2                   770
#define TRAINER_ROXANNE_3                   771
#define TRAINER_ROXANNE_4                   772
#define TRAINER_ROXANNE_5                   773
#define TRAINER_BRAWLY_2                    774
#define TRAINER_BRAWLY_3                    775
#define TRAINER_BRAWLY_4                    776
#define TRAINER_BRAWLY_5                    777
#define TRAINER_WATTSON_2                   778
#define TRAINER_WATTSON_3                   779
#define TRAINER_WATTSON_4                   780
#define TRAINER_WATTSON_5                   781
#define TRAINER_FLANNERY_2                  782
#define TRAINER_FLANNERY_3                  783
#define TRAINER_FLANNERY_4                  784
#define TRAINER_FLANNERY_5                  785
#define TRAINER_NORMAN_2                    786
#define TRAINER_NORMAN_3                    787
#define TRAINER_NORMAN_4                    788
#define TRAINER_NORMAN_5                    789
#define TRAINER_WINONA_2                    790
#define TRAINER_WINONA_3                    791
#define TRAINER_WINONA_4                    792
#define TRAINER_WINONA_5                    793
#define TRAINER_TATE_AND_LIZA_2             794
#define TRAINER_TATE_AND_LIZA_3             795
#define TRAINER_TATE_AND_LIZA_4             796
#define TRAINER_TATE_AND_LIZA_5             797
#define TRAINER_JUAN_2                      798
#define TRAINER_JUAN_3                      799
#define TRAINER_JUAN_4                      800
#define TRAINER_JUAN_5                      801
#define TRAINER_ANGELO                      802
#define TRAINER_DARIUS                      803
#define TRAINER_STEVEN                      804
#define TRAINER_ANABEL                      805
#define TRAINER_TUCKER                      806
#define TRAINER_SPENSER                     807
#define TRAINER_GRETA                       808
#define TRAINER_NOLAND                      809
#define TRAINER_LUCY                        810
#define TRAINER_BRANDON                     811
#define TRAINER_ANDRES_2                    812
#define TRAINER_ANDRES_3                    813
#define TRAINER_ANDRES_4                    814
#define TRAINER_ANDRES_5                    815
#define TRAINER_CORY_2                      816
#define TRAINER_CORY_3                      817
#define TRAINER_CORY_4                      818
#define TRAINER_CORY_5                      819
#define TRAINER_PABLO_2                     820
#define TRAINER_PABLO_3                     821
#define TRAINER_PABLO_4                     822
#define TRAINER_PABLO_5                     823
#define TRAINER_KOJI_2                      824
#define TRAINER_KOJI_3                      825
#define TRAINER_KOJI_4                      826
#define TRAINER_KOJI_5                      827
#define TRAINER_CRISTIN_2                   828
#define TRAINER_CRISTIN_3                   829
#define TRAINER_CRISTIN_4                   830
#define TRAINER_CRISTIN_5                   831
#define TRAINER_FERNANDO_2                  832
#define TRAINER_FERNANDO_3                  833
#define TRAINER_FERNANDO_4                  834
#define TRAINER_FERNANDO_5                  835
#define TRAINER_SAWYER_2                    836
#define TRAINER_SAWYER_3                    837
#define TRAINER_SAWYER_4                    838
#define TRAINER_SAWYER_5                    839
#define TRAINER_GABRIELLE_2                 840
#define TRAINER_GABRIELLE_3                 841
#define TRAINER_GABRIELLE_4                 842
#define TRAINER_GABRIELLE_5                 843
#define TRAINER_THALIA_2                    844
#define TRAINER_THALIA_3                    845
#define TRAINER_THALIA_4                    846
#define TRAINER_THALIA_5                    847
#define TRAINER_MARIELA                     848
#define TRAINER_ALVARO                      849
#define TRAINER_EVERETT                     850
#define TRAINER_RED                         851
#define TRAINER_LEAF                        852
#define TRAINER_BRENDAN_PLACEHOLDER         853
#define TRAINER_MAY_PLACEHOLDER             854

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      855
#define MAX_TRAINERS_COUNT                  864
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
