KalamiCity_House3_MapScripts::
	.byte 0


KalamiCity_House3_EventScript_Woman::
# 5 "data/maps/KalamiCity_House3/scripts.pory"
	lock
# 6 "data/maps/KalamiCity_House3/scripts.pory"
	faceplayer
# 7 "data/maps/KalamiCity_House3/scripts.pory"
	speakername KalamiCity_House3_EventScript_Woman_Text_0
# 8 "data/maps/KalamiCity_House3/scripts.pory"
	msgbox KalamiCity_House3_EventScript_Woman_Text_1
# 9 "data/maps/KalamiCity_House3/scripts.pory"
	closemessage
# 10 "data/maps/KalamiCity_House3/scripts.pory"
	release
	end


KalamiCity_House3_EventScript_Scientist::
# 16 "data/maps/KalamiCity_House3/scripts.pory"
	lock
# 17 "data/maps/KalamiCity_House3/scripts.pory"
	faceplayer
# 18 "data/maps/KalamiCity_House3/scripts.pory"
	speakername KalamiCity_House3_EventScript_Scientist_Text_0
# 19 "data/maps/KalamiCity_House3/scripts.pory"
	msgbox KalamiCity_House3_EventScript_Scientist_Text_1
# 20 "data/maps/KalamiCity_House3/scripts.pory"
	closemessage
# 21 "data/maps/KalamiCity_House3/scripts.pory"
	release
	end


KalamiCity_House3_EventScript_Reporter::
# 27 "data/maps/KalamiCity_House3/scripts.pory"
	lock
# 28 "data/maps/KalamiCity_House3/scripts.pory"
	faceplayer
# 29 "data/maps/KalamiCity_House3/scripts.pory"
	speakername KalamiCity_House3_EventScript_Reporter_Text_0
# 30 "data/maps/KalamiCity_House3/scripts.pory"
	msgbox KalamiCity_House3_EventScript_Reporter_Text_1
# 31 "data/maps/KalamiCity_House3/scripts.pory"
	closemessage
# 32 "data/maps/KalamiCity_House3/scripts.pory"
	release
	end


KalamiCity_House3_EventScript_ScientistF::
# 38 "data/maps/KalamiCity_House3/scripts.pory"
	lock
# 39 "data/maps/KalamiCity_House3/scripts.pory"
	faceplayer
# 40 "data/maps/KalamiCity_House3/scripts.pory"
	speakername KalamiCity_House3_EventScript_Scientist_Text_0
# 41 "data/maps/KalamiCity_House3/scripts.pory"
	msgbox KalamiCity_House3_EventScript_ScientistF_Text_0
# 42 "data/maps/KalamiCity_House3/scripts.pory"
	closemessage
# 43 "data/maps/KalamiCity_House3/scripts.pory"
	release
	end


KalamiCity_House3_EventScript_Woman_Text_0:
# 7 "data/maps/KalamiCity_House3/scripts.pory"
	.string "Woman$"

KalamiCity_House3_EventScript_Woman_Text_1:
# 8 "data/maps/KalamiCity_House3/scripts.pory"
	.string "This is the locally-run data processing\n"
	.string "center for the Kalami City trade ports.\l"
	.string "We keep track of everything that goes\l"
	.string "through the city.$"

KalamiCity_House3_EventScript_Scientist_Text_0:
# 18 "data/maps/KalamiCity_House3/scripts.pory"
	.string "Scientist$"

KalamiCity_House3_EventScript_Scientist_Text_1:
# 19 "data/maps/KalamiCity_House3/scripts.pory"
	.string "I manage all the spreadsheets for the\n"
	.string "city! It's stressful sometimes, but the\l"
	.string "work environment is nice. I've got my\l"
	.string "own flower box!$"

KalamiCity_House3_EventScript_Reporter_Text_0:
# 29 "data/maps/KalamiCity_House3/scripts.pory"
	.string "Man$"

KalamiCity_House3_EventScript_Reporter_Text_1:
# 30 "data/maps/KalamiCity_House3/scripts.pory"
	.string "I'm getting tired of looking at this\n"
	.string "screen... maybe I'll take a break and\l"
	.string "read for a bit.$"

KalamiCity_House3_EventScript_ScientistF_Text_0:
# 41 "data/maps/KalamiCity_House3/scripts.pory"
	.string "I help manage the data processing\n"
	.string "center. Mattaios, the Gym Leader of\l"
	.string "Kalami City, also likes to stay involved\l"
	.string "in the running of the city.$"
