gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Professor Elia.\p"
	.string "I study paleontology and archaic\n"
	.string "remains at Acrisia University.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Here, take a look at this guy...\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This Pokémon, Archen, was widely\n"
	.string "thought to be extinct. It was\l"
	.string "only known from fossils until now.\p"
	.string "These species are known as Lazarus\n"
	.string "Taxa, as from the perspective of\l"
	.string "science, they're back from the dead.\p"
	.string "I believe that Pokémon are the key\n"
	.string "to living in harmony with our\l"
	.string "natural environments.\p"
	.string "Of course, these Lazarus Taxa\n"
	.string "aren't the only groups we study.\p"
	.string "At the Acrisia University, we\n"
	.string "want to learn as much as we can\l"
	.string "about all Pokémon.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Let's do some paperwork.$"

gText_Birch_BoyOrGirl::
	.string "Which applicant are you?\n"
	.string "$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Of course, {PLAYER}!\p"
	.string "We've reviewed your application\n"
	.string "and we're excited to have you\l"
	.string "here!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "The Ilios Region is full to\n"
	.string "bursting with secrets to find and\l"
	.string "new locations to explore!\p"
	.string "Your new career as a research\n"
	.string "assistant and Pokémon Trainer\l"
	.string "starts now!\p"
	.string "$"
