gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the Alola Region!\p"
	.string "My name is Burnet.\p"
	.string "But everyone calls me the Pokémon\n"
	.string "Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a Pokémon.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This Region is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "In Alola, we live alongside Pokémon,\n"
	.string "becoming great friends and even\l"
	.string "cooperating to thrive together.\p"
	.string "Our traditions make us closer to\n"
	.string "our Pokémon than anyone else.\p"
	.string "My husband Kukui and I both\n"
	.string "study Pokémon, and we're\l"
	.string "always learning more.\p"
	.string "Between Pokémon migrations, new\n"
	.string "introductions, and surprising\l"
	.string "finds, there's always more to study!\p"
	.string "In fact, we're looking for promising\n"
	.string "Trainers to help.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now, let's do some paperwork.$"

gText_Birch_BoyOrGirl::
	.string "Which picture should we use\n"
	.string "for your passport?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "Could you spell out your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}, yeah?$"

gText_Birch_YourePlayer::
	.string "-Snap- Of course!\p"
	.string "You're {PLAYER}{KUN}, Samson's\n"
	.string "grandkid, moving in right by\l"
	.string "Hau'oli City. Gotcha!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "The Masked Royal is about to battle\n"
	.string "on TV, so I have to go!\p"
	.string "Between discovering Pokémon, exploring\n"
	.string "Alola, and making new friends, you'll\l"
	.string "never forget your time here!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "See you soon, cousin!\p"
	.string "$"
