WanderersWoods_MapScripts::
	.byte 0


WanderersWoods_EventScript_Trainer_WanderersWoods_Zander::
# 5 "data/maps/WanderersWoods/scripts.pory"
	trainerbattle_single TRAINER_WANDERERSWOODS_ZANDER, WanderersWoods_Text_Trainer_WanderersWoods_ZanderIntro, WanderersWoods_Text_Trainer_WanderersWoods_ZanderDefeat
# 6 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_Trainer_WanderersWoods_Zander_Text_0
# 7 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_Trainer_WanderersWoods_Zander_Text_1
# 8 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 9 "data/maps/WanderersWoods/scripts.pory"
	release
	end


WanderersWoods_EventScript_Trainer_WanderersWoods_Kallas::
# 23 "data/maps/WanderersWoods/scripts.pory"
	trainerbattle_single TRAINER_WANDERERSWOODS_KALLAS, WanderersWoods_Text_Trainer_WanderersWoods_KallasIntro, WanderersWoods_Text_Trainer_WanderersWoods_KallasDefeat
# 24 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_Trainer_WanderersWoods_Kallas_Text_0
# 25 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_Trainer_WanderersWoods_Kallas_Text_1
# 26 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 27 "data/maps/WanderersWoods/scripts.pory"
	release
	end


WanderersWoods_EventScript_Trainer_WanderersWoods_Martha::
# 41 "data/maps/WanderersWoods/scripts.pory"
	trainerbattle_single TRAINER_WANDERERSWOODS_MARTHA, WanderersWoods_Text_Trainer_WanderersWoods_MarthaIntro, WanderersWoods_Text_Trainer_WanderersWoods_MarthaDefeat
# 42 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_Trainer_WanderersWoods_Martha_Text_0
# 43 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_Trainer_WanderersWoods_Martha_Text_1
# 44 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 45 "data/maps/WanderersWoods/scripts.pory"
	release
	end


WanderersWoods_EventScript_Trainer_WanderersWoods_Alexi::
# 59 "data/maps/WanderersWoods/scripts.pory"
	trainerbattle_single TRAINER_WANDERERSWOODS_ALEXI, WanderersWoods_Text_Trainer_WanderersWoods_AlexiIntro, WanderersWoods_Text_Trainer_WanderersWoods_AlexiDefeat
# 60 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_Trainer_WanderersWoods_Alexi_Text_0
# 61 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_Trainer_WanderersWoods_Alexi_Text_1
# 62 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 63 "data/maps/WanderersWoods/scripts.pory"
	release
	end


WanderersWoods_EventScript_Trainer_WanderersWoods_Ellie::
# 77 "data/maps/WanderersWoods/scripts.pory"
	trainerbattle_single TRAINER_WANDERERSWOODS_ELLIE, WanderersWoods_Text_Trainer_WanderersWoods_EllieIntro, WanderersWoods_Text_Trainer_WanderersWoods_EllieDefeat
# 78 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_Trainer_WanderersWoods_Ellie_Text_0
# 79 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_Trainer_WanderersWoods_Ellie_Text_1
# 80 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 81 "data/maps/WanderersWoods/scripts.pory"
	release
	end


WanderersWoods_EventScript_Trainer_WanderersWoods_Lydia::
# 95 "data/maps/WanderersWoods/scripts.pory"
	trainerbattle_single TRAINER_WANDERERSWOODS_LYDIA, WanderersWoods_Text_Trainer_WanderersWoods_LydiaIntro, WanderersWoods_Text_Trainer_WanderersWoods_LydiaDefeat
# 96 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_Trainer_WanderersWoods_Lydia_Text_0
# 97 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_Trainer_WanderersWoods_Lydia_Text_1
# 98 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 99 "data/maps/WanderersWoods/scripts.pory"
	release
	end


WanderersWoods_EventScript_Trainer_WanderersWoods_Thomas::
# 113 "data/maps/WanderersWoods/scripts.pory"
	trainerbattle_single TRAINER_WANDERERSWOODS_THOMAS, WanderersWoods_Text_Trainer_WanderersWoods_ThomasIntro, WanderersWoods_Text_Trainer_WanderersWoods_ThomasDefeat
# 114 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_Trainer_WanderersWoods_Thomas_Text_0
# 115 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_Trainer_WanderersWoods_Thomas_Text_1
# 116 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 117 "data/maps/WanderersWoods/scripts.pory"
	release
	end


WanderersWoods_EventScript_NPC_Man::
# 131 "data/maps/WanderersWoods/scripts.pory"
	lock
# 132 "data/maps/WanderersWoods/scripts.pory"
	faceplayer
# 133 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_NPC_Man_Text_0
# 134 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_NPC_Man_Text_1
# 135 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 136 "data/maps/WanderersWoods/scripts.pory"
	release
	end


WanderersWoods_EventScript_RaniaNPC::
# 142 "data/maps/WanderersWoods/scripts.pory"
	lock
# 143 "data/maps/WanderersWoods/scripts.pory"
	faceplayer
# 144 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_RaniaNPC_Text_0
# 145 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_RaniaNPC_Text_1
# 146 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 147 "data/maps/WanderersWoods/scripts.pory"
	release
	end


WanderersWoods_EventScript_NikoNPC::
# 153 "data/maps/WanderersWoods/scripts.pory"
	lock
# 154 "data/maps/WanderersWoods/scripts.pory"
	faceplayer
# 155 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_NikoNPC_Text_0
# 156 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_NikoNPC_Text_1
# 157 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 158 "data/maps/WanderersWoods/scripts.pory"
	release
	end


WanderersWoods_Trigger_ChimeraEvent::
# 169 "data/maps/WanderersWoods/scripts.pory"
	lock
# 170 "data/maps/WanderersWoods/scripts.pory"
	applymovement 6, Common_Movement_WalkDown
# 171 "data/maps/WanderersWoods/scripts.pory"
	applymovement 7, Common_Movement_WalkDown
# 172 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 173 "data/maps/WanderersWoods/scripts.pory"
	applymovement 7, Common_Movement_WalkRight
# 174 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 175 "data/maps/WanderersWoods/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_FaceUp
# 176 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 177 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_RaniaNPC_Text_0
# 178 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_Trigger_ChimeraEvent_Text_0
# 179 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 180 "data/maps/WanderersWoods/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_FaceLeft
# 181 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 182 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_NikoNPC_Text_0
# 183 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_Trigger_ChimeraEvent_Text_1
# 184 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 185 "data/maps/WanderersWoods/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, WanderersWoods_Movement_PlayerLeadsToChimera
# 186 "data/maps/WanderersWoods/scripts.pory"
	applymovement 6, WanderersWoods_Movement_RaniaFollowsToChimera
# 187 "data/maps/WanderersWoods/scripts.pory"
	applymovement 7, WanderersWoods_Movement_NikoFollowsToChimera
# 188 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 189 "data/maps/WanderersWoods/scripts.pory"
	goto WanderersWoods_EventScript_ChimeraEvent
	end


WanderersWoods_EventScript_ChimeraEvent::
# 196 "data/maps/WanderersWoods/scripts.pory"
	delay 20
# 197 "data/maps/WanderersWoods/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_FaceDown
# 198 "data/maps/WanderersWoods/scripts.pory"
	applymovement 7, Common_Movement_FaceDown
# 199 "data/maps/WanderersWoods/scripts.pory"
	applymovement 6, Common_Movement_FaceDown
# 200 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 201 "data/maps/WanderersWoods/scripts.pory"
	applymovement 7, Common_Movement_ExclamationMark
# 202 "data/maps/WanderersWoods/scripts.pory"
	applymovement 6, Common_Movement_ExclamationMark
# 203 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 204 "data/maps/WanderersWoods/scripts.pory"
	delay 30
# 207 "data/maps/WanderersWoods/scripts.pory"
	applymovement 6, Common_Movement_FaceLeft
# 208 "data/maps/WanderersWoods/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_FaceRight
# 209 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 210 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_RaniaNPC_Text_0
# 211 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_ChimeraEvent_Text_0
# 212 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 213 "data/maps/WanderersWoods/scripts.pory"
	applymovement 6, Common_Movement_FaceDown
# 214 "data/maps/WanderersWoods/scripts.pory"
	applymovement 7, Common_Movement_FaceDown
# 215 "data/maps/WanderersWoods/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_FaceDown
# 216 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 219 "data/maps/WanderersWoods/scripts.pory"
	applymovement 8, Common_Movement_WalkUp
# 220 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 221 "data/maps/WanderersWoods/scripts.pory"
	delay 15
# 222 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_ChimeraEvent_Text_1
# 223 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_ChimeraEvent_Text_2
# 224 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 225 "data/maps/WanderersWoods/scripts.pory"
	delay 15
# 226 "data/maps/WanderersWoods/scripts.pory"
	applymovement 9, Common_Movement_WalkUp2
# 227 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 228 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_ChimeraEvent_Text_1
# 229 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_ChimeraEvent_Text_3
# 230 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 231 "data/maps/WanderersWoods/scripts.pory"
	applymovement 10, Common_Movement_ExclamationMark
# 232 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 233 "data/maps/WanderersWoods/scripts.pory"
	applymovement 10, Common_Movement_FaceRight
# 234 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 235 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_ChimeraEvent_Text_4
# 236 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_ChimeraEvent_Text_5
# 237 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 240 "data/maps/WanderersWoods/scripts.pory"
	applymovement 11, Common_Movement_JumpInPlaceLeft
# 241 "data/maps/WanderersWoods/scripts.pory"
	applymovement 12, Common_Movement_JumpInPlaceDown
# 242 "data/maps/WanderersWoods/scripts.pory"
	applymovement 13, Common_Movement_JumpInPlaceLeft
# 243 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 244 "data/maps/WanderersWoods/scripts.pory"
	delay 20
# 245 "data/maps/WanderersWoods/scripts.pory"
	applymovement 10, Common_Movement_ExclamationMark
# 246 "data/maps/WanderersWoods/scripts.pory"
	applymovement 8, Common_Movement_FaceDown
# 247 "data/maps/WanderersWoods/scripts.pory"
	applymovement 9, Common_Movement_FaceDown
# 248 "data/maps/WanderersWoods/scripts.pory"
	applymovement 10, Common_Movement_FaceDown
# 249 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 250 "data/maps/WanderersWoods/scripts.pory"
	applymovement 11, WanderersWoods_Movement_ShroomishEscape
# 251 "data/maps/WanderersWoods/scripts.pory"
	applymovement 12, WanderersWoods_Movement_BlitzleEscape
# 252 "data/maps/WanderersWoods/scripts.pory"
	applymovement 13, WanderersWoods_Movement_ImpidimpEscape
# 253 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 254 "data/maps/WanderersWoods/scripts.pory"
	delay 60
# 257 "data/maps/WanderersWoods/scripts.pory"
	applymovement 8, Common_Movement_FaceUp
# 258 "data/maps/WanderersWoods/scripts.pory"
	applymovement 9, Common_Movement_FaceUp
# 259 "data/maps/WanderersWoods/scripts.pory"
	applymovement 10, Common_Movement_FaceUp
# 260 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_ChimeraEvent_Text_4
# 261 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_ChimeraEvent_Text_6
# 262 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 263 "data/maps/WanderersWoods/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_FaceRight
# 264 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 265 "data/maps/WanderersWoods/scripts.pory"
	applymovement 6, Common_Movement_FaceLeft
# 266 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 267 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_RaniaNPC_Text_0
# 268 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_ChimeraEvent_Text_7
# 269 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 270 "data/maps/WanderersWoods/scripts.pory"
	applymovement 6, Common_Movement_FaceDown
# 271 "data/maps/WanderersWoods/scripts.pory"
	applymovement 7, Common_Movement_FaceDown
# 272 "data/maps/WanderersWoods/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_FaceDown
# 275 "data/maps/WanderersWoods/scripts.pory"
	applymovement 8, Common_Movement_WalkUp
# 276 "data/maps/WanderersWoods/scripts.pory"
	applymovement 9, Common_Movement_WalkUp
# 277 "data/maps/WanderersWoods/scripts.pory"
	applymovement 10, Common_Movement_WalkUp
# 278 "data/maps/WanderersWoods/scripts.pory"
	compare VAR_DIFFICULTY, 0
	goto_if_eq WanderersWoods_EventScript_ChimeraEvent_2
# 284 "data/maps/WanderersWoods/scripts.pory"
	trainerbattle_no_intro TRAINER_WANDERERSWOODS_CHIMERA_ADMIN_HARD, WanderersWoods_Text_ChimeraAdminDefeated
WanderersWoods_EventScript_ChimeraEvent_1:
# 288 "data/maps/WanderersWoods/scripts.pory"
	applymovement 10, Common_Movement_QuestionMark
# 289 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 290 "data/maps/WanderersWoods/scripts.pory"
	applymovement 10, Common_Movement_FaceLeft
# 291 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 292 "data/maps/WanderersWoods/scripts.pory"
	applymovement 8, WanderersWoods_Movement_GruntEscapes1
# 293 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 294 "data/maps/WanderersWoods/scripts.pory"
	applymovement 7, Common_Movement_WalkDown
# 295 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 296 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_NikoNPC_Text_0
# 297 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_ChimeraEvent_Text_8
# 298 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 299 "data/maps/WanderersWoods/scripts.pory"
	applymovement 7, WanderersWoods_Movement_GruntEscapes1
# 300 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 301 "data/maps/WanderersWoods/scripts.pory"
	delay 20
# 302 "data/maps/WanderersWoods/scripts.pory"
	applymovement 10, Common_Movement_ExclamationMark
# 303 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 304 "data/maps/WanderersWoods/scripts.pory"
	applymovement 10, Common_Movement_FaceRight
# 305 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 306 "data/maps/WanderersWoods/scripts.pory"
	applymovement 9, WanderersWoods_Movement_GruntEscapes2
# 307 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 308 "data/maps/WanderersWoods/scripts.pory"
	applymovement 6, Common_Movement_WalkDown
# 309 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 310 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_RaniaNPC_Text_0
# 311 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_ChimeraEvent_Text_9
# 312 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 313 "data/maps/WanderersWoods/scripts.pory"
	applymovement 6, WanderersWoods_Movement_GruntEscapes2
# 314 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 315 "data/maps/WanderersWoods/scripts.pory"
	delay 60
# 318 "data/maps/WanderersWoods/scripts.pory"
	applymovement 10, Common_Movement_FaceUp
# 319 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 320 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_ChimeraEvent_Text_4
# 321 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_ChimeraEvent_Text_10
# 322 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 323 "data/maps/WanderersWoods/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_ExclamationMark
# 324 "data/maps/WanderersWoods/scripts.pory"
	applymovement 10, WanderersWoods_Movement_AdminEscapes
# 325 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 326 "data/maps/WanderersWoods/scripts.pory"
	delay 20
# 329 "data/maps/WanderersWoods/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkDown
# 330 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 331 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_ChimeraEvent_Text_11
# 332 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_ChimeraEvent_Text_12
# 333 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 334 "data/maps/WanderersWoods/scripts.pory"
	delay 30
# 335 "data/maps/WanderersWoods/scripts.pory"
	message WanderersWoods_EventScript_ChimeraEvent_Text_13
# 336 "data/maps/WanderersWoods/scripts.pory"
	waitmessage
# 337 "data/maps/WanderersWoods/scripts.pory"
	multichoice 21, 8, MULTI_NIKO_OR_RANIA, TRUE
# 338 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 339 "data/maps/WanderersWoods/scripts.pory"
	fadescreenswapbuffers FADE_TO_BLACK
# 340 "data/maps/WanderersWoods/scripts.pory"
	delay 20
# 341 "data/maps/WanderersWoods/scripts.pory"
	addobject 7
# 342 "data/maps/WanderersWoods/scripts.pory"
	applymovement 7, WanderersWoods_Movement_NikoReturns
# 343 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 344 "data/maps/WanderersWoods/scripts.pory"
	addobject 6
# 345 "data/maps/WanderersWoods/scripts.pory"
	applymovement 6, WanderersWoods_Movement_RaniaReturns
# 346 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 347 "data/maps/WanderersWoods/scripts.pory"
	delay 10
# 348 "data/maps/WanderersWoods/scripts.pory"
	fadescreenswapbuffers FADE_FROM_BLACK
# 349 "data/maps/WanderersWoods/scripts.pory"
	delay 30
# 352 "data/maps/WanderersWoods/scripts.pory"
	compare VAR_RESULT, 0
	goto_if_eq WanderersWoods_EventScript_ChimeraEvent_6
# 372 "data/maps/WanderersWoods/scripts.pory"
	applymovement 6, Common_Movement_FaceLeft
# 373 "data/maps/WanderersWoods/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_FaceRight
# 374 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 375 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_RaniaNPC_Text_0
# 376 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_ChimeraEvent_Text_14
# 377 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 378 "data/maps/WanderersWoods/scripts.pory"
	giveegg SPECIES_COSMOG
# 379 "data/maps/WanderersWoods/scripts.pory"
	playfanfare MUS_OBTAIN_ITEM
# 380 "data/maps/WanderersWoods/scripts.pory"
	message WanderersWoods_EventScript_ChimeraEvent_Text_15
# 381 "data/maps/WanderersWoods/scripts.pory"
	waitmessage
# 382 "data/maps/WanderersWoods/scripts.pory"
	waitfanfare
# 383 "data/maps/WanderersWoods/scripts.pory"
	delay 20
# 384 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_RaniaNPC_Text_0
# 385 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_ChimeraEvent_Text_17
# 386 "data/maps/WanderersWoods/scripts.pory"
	closemessage
WanderersWoods_EventScript_ChimeraEvent_5:
# 390 "data/maps/WanderersWoods/scripts.pory"
	fadescreenswapbuffers FADE_TO_BLACK
# 391 "data/maps/WanderersWoods/scripts.pory"
	delay 30
# 392 "data/maps/WanderersWoods/scripts.pory"
	setflag FLAG_BEAT_CHIMERA_WANDERING_WOODS
# 393 "data/maps/WanderersWoods/scripts.pory"
	removeobject 6
# 394 "data/maps/WanderersWoods/scripts.pory"
	removeobject 7
# 395 "data/maps/WanderersWoods/scripts.pory"
	removeobject 8
# 396 "data/maps/WanderersWoods/scripts.pory"
	removeobject 9
# 397 "data/maps/WanderersWoods/scripts.pory"
	removeobject 10
# 398 "data/maps/WanderersWoods/scripts.pory"
	removeobject 11
# 399 "data/maps/WanderersWoods/scripts.pory"
	removeobject 12
# 400 "data/maps/WanderersWoods/scripts.pory"
	removeobject 13
# 401 "data/maps/WanderersWoods/scripts.pory"
	delay 30
# 402 "data/maps/WanderersWoods/scripts.pory"
	fadescreenswapbuffers FADE_FROM_BLACK
# 403 "data/maps/WanderersWoods/scripts.pory"
	delay 30
# 404 "data/maps/WanderersWoods/scripts.pory"
	releaseall
	end

WanderersWoods_EventScript_ChimeraEvent_2:
# 280 "data/maps/WanderersWoods/scripts.pory"
	trainerbattle_no_intro TRAINER_WANDERERSWOODS_CHIMERA_ADMIN, WanderersWoods_Text_ChimeraAdminDefeated
	goto WanderersWoods_EventScript_ChimeraEvent_1

WanderersWoods_EventScript_ChimeraEvent_6:
# 354 "data/maps/WanderersWoods/scripts.pory"
	applymovement 7, Common_Movement_FaceRight
# 355 "data/maps/WanderersWoods/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_FaceLeft
# 356 "data/maps/WanderersWoods/scripts.pory"
	waitmovement 0
# 357 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_NikoNPC_Text_0
# 358 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_ChimeraEvent_Text_14
# 359 "data/maps/WanderersWoods/scripts.pory"
	closemessage
# 360 "data/maps/WanderersWoods/scripts.pory"
	giveegg SPECIES_ZYGARDE_CELL
# 361 "data/maps/WanderersWoods/scripts.pory"
	playfanfare MUS_OBTAIN_ITEM
# 362 "data/maps/WanderersWoods/scripts.pory"
	message WanderersWoods_EventScript_ChimeraEvent_Text_15
# 363 "data/maps/WanderersWoods/scripts.pory"
	waitmessage
# 364 "data/maps/WanderersWoods/scripts.pory"
	waitfanfare
# 365 "data/maps/WanderersWoods/scripts.pory"
	delay 20
# 366 "data/maps/WanderersWoods/scripts.pory"
	speakername WanderersWoods_EventScript_NikoNPC_Text_0
# 367 "data/maps/WanderersWoods/scripts.pory"
	msgbox WanderersWoods_EventScript_ChimeraEvent_Text_16
# 368 "data/maps/WanderersWoods/scripts.pory"
	closemessage
	goto WanderersWoods_EventScript_ChimeraEvent_5


# 408 "data/maps/WanderersWoods/scripts.pory"
WanderersWoods_Movement_PlayerLeadsToChimera:
# 410 "data/maps/WanderersWoods/scripts.pory"
	walk_right
# 410 "data/maps/WanderersWoods/scripts.pory"
	walk_right
# 411 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 411 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 411 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 412 "data/maps/WanderersWoods/scripts.pory"
	emote_question_mark
# 413 "data/maps/WanderersWoods/scripts.pory"
	delay_16
# 414 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 414 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 415 "data/maps/WanderersWoods/scripts.pory"
	step_end

# 418 "data/maps/WanderersWoods/scripts.pory"
WanderersWoods_Movement_RaniaFollowsToChimera:
# 420 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 421 "data/maps/WanderersWoods/scripts.pory"
	walk_right
# 421 "data/maps/WanderersWoods/scripts.pory"
	walk_right
# 422 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 422 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 423 "data/maps/WanderersWoods/scripts.pory"
	delay_16
# 424 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 424 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 425 "data/maps/WanderersWoods/scripts.pory"
	walk_right
# 426 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 427 "data/maps/WanderersWoods/scripts.pory"
	step_end

# 430 "data/maps/WanderersWoods/scripts.pory"
WanderersWoods_Movement_NikoFollowsToChimera:
# 432 "data/maps/WanderersWoods/scripts.pory"
	walk_in_place_right
# 433 "data/maps/WanderersWoods/scripts.pory"
	walk_right
# 433 "data/maps/WanderersWoods/scripts.pory"
	walk_right
# 434 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 434 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 434 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 435 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 435 "data/maps/WanderersWoods/scripts.pory"
	walk_down
# 436 "data/maps/WanderersWoods/scripts.pory"
	step_end

# 439 "data/maps/WanderersWoods/scripts.pory"
WanderersWoods_Movement_ShroomishEscape:
# 441 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 442 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_up
# 443 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 443 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 443 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 443 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 443 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 443 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 443 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 444 "data/maps/WanderersWoods/scripts.pory"
	step_end

# 447 "data/maps/WanderersWoods/scripts.pory"
WanderersWoods_Movement_BlitzleEscape:
# 449 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 449 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 450 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 450 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 451 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 451 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 452 "data/maps/WanderersWoods/scripts.pory"
	step_end

# 455 "data/maps/WanderersWoods/scripts.pory"
WanderersWoods_Movement_ImpidimpEscape:
# 457 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 458 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 458 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 459 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_up
# 460 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 460 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 460 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 461 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 461 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 461 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 461 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 462 "data/maps/WanderersWoods/scripts.pory"
	step_end

# 470 "data/maps/WanderersWoods/scripts.pory"
WanderersWoods_Movement_GruntEscapes1:
# 472 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 472 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 473 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 473 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 474 "data/maps/WanderersWoods/scripts.pory"
	jump_down
# 474 "data/maps/WanderersWoods/scripts.pory"
	jump_down
# 474 "data/maps/WanderersWoods/scripts.pory"
	jump_down
# 475 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 475 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 475 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 476 "data/maps/WanderersWoods/scripts.pory"
	step_end

# 479 "data/maps/WanderersWoods/scripts.pory"
WanderersWoods_Movement_GruntEscapes2:
# 481 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 481 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 481 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 482 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 482 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 483 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 483 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 484 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 485 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 485 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 486 "data/maps/WanderersWoods/scripts.pory"
	step_end

# 489 "data/maps/WanderersWoods/scripts.pory"
WanderersWoods_Movement_AdminEscapes:
# 491 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 491 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 491 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 491 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 491 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 492 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 492 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 492 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_left
# 493 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 493 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 493 "data/maps/WanderersWoods/scripts.pory"
	walk_fast_down
# 494 "data/maps/WanderersWoods/scripts.pory"
	step_end

# 497 "data/maps/WanderersWoods/scripts.pory"
WanderersWoods_Movement_NikoReturns:
# 499 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_up
# 499 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_up
# 499 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_up
# 500 "data/maps/WanderersWoods/scripts.pory"
	jump_up
# 500 "data/maps/WanderersWoods/scripts.pory"
	jump_up
# 500 "data/maps/WanderersWoods/scripts.pory"
	jump_up
# 501 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_right
# 501 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_right
# 502 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_up
# 502 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_up
# 503 "data/maps/WanderersWoods/scripts.pory"
	face_right
# 504 "data/maps/WanderersWoods/scripts.pory"
	step_end

# 507 "data/maps/WanderersWoods/scripts.pory"
WanderersWoods_Movement_RaniaReturns:
# 509 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_up
# 509 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_up
# 510 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_right
# 511 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_up
# 511 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_up
# 512 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_right
# 512 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_right
# 513 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_up
# 513 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_up
# 513 "data/maps/WanderersWoods/scripts.pory"
	walk_faster_up
# 514 "data/maps/WanderersWoods/scripts.pory"
	face_left
# 515 "data/maps/WanderersWoods/scripts.pory"
	step_end

WanderersWoods_EventScript_Trainer_WanderersWoods_Zander_Text_0:
# 6 "data/maps/WanderersWoods/scripts.pory"
	.string "Zander$"

WanderersWoods_EventScript_Trainer_WanderersWoods_Zander_Text_1:
# 7 "data/maps/WanderersWoods/scripts.pory"
	.string "Apparently people get lost in here all\n"
	.string "the time. I'm not letting Jusmail Town\l"
	.string "out of my sight!$"

WanderersWoods_EventScript_Trainer_WanderersWoods_Kallas_Text_0:
# 24 "data/maps/WanderersWoods/scripts.pory"
	.string "Kallas$"

WanderersWoods_EventScript_Trainer_WanderersWoods_Kallas_Text_1:
# 25 "data/maps/WanderersWoods/scripts.pory"
	.string "These Grass-type Pokémon are weak to\n"
	.string "my Flying-type moves.$"

WanderersWoods_EventScript_Trainer_WanderersWoods_Martha_Text_0:
# 42 "data/maps/WanderersWoods/scripts.pory"
	.string "Martha$"

WanderersWoods_EventScript_Trainer_WanderersWoods_Martha_Text_1:
# 43 "data/maps/WanderersWoods/scripts.pory"
	.string "There are rumors of Team Chimera\n"
	.string "operating around here recently.$"

WanderersWoods_EventScript_Trainer_WanderersWoods_Alexi_Text_0:
# 60 "data/maps/WanderersWoods/scripts.pory"
	.string "Alexi$"

WanderersWoods_EventScript_Trainer_WanderersWoods_Alexi_Text_1:
# 61 "data/maps/WanderersWoods/scripts.pory"
	.string "How do people get through here,\n"
	.string "anyway? Ugh.$"

WanderersWoods_EventScript_Trainer_WanderersWoods_Ellie_Text_0:
# 78 "data/maps/WanderersWoods/scripts.pory"
	.string "Ellie$"

WanderersWoods_EventScript_Trainer_WanderersWoods_Ellie_Text_1:
# 79 "data/maps/WanderersWoods/scripts.pory"
	.string "Some Pokémon only come out at night.\n"
	.string "Maybe my music will bring out the\l"
	.string "coolest Pokémon!$"

WanderersWoods_EventScript_Trainer_WanderersWoods_Lydia_Text_0:
# 96 "data/maps/WanderersWoods/scripts.pory"
	.string "Lydia$"

WanderersWoods_EventScript_Trainer_WanderersWoods_Lydia_Text_1:
# 97 "data/maps/WanderersWoods/scripts.pory"
	.string "Team Chimera was in the woods?! Their\n"
	.string "treatment of Pokémon is known to be\l"
	.string "terrible.$"

WanderersWoods_EventScript_Trainer_WanderersWoods_Thomas_Text_0:
# 114 "data/maps/WanderersWoods/scripts.pory"
	.string "Thomas$"

WanderersWoods_EventScript_Trainer_WanderersWoods_Thomas_Text_1:
# 115 "data/maps/WanderersWoods/scripts.pory"
	.string "Not all Ghost-type or Dark-type\n"
	.string "Pokémon are actually evil! That's a\l"
	.string "common misconception.$"

WanderersWoods_EventScript_NPC_Man_Text_0:
# 133 "data/maps/WanderersWoods/scripts.pory"
	.string "Man$"

WanderersWoods_EventScript_NPC_Man_Text_1:
# 134 "data/maps/WanderersWoods/scripts.pory"
	.string "I think I finally found the way out of\n"
	.string "the woods! These red-orange plants are\l"
	.string "a sure sign of Pythios Town.$"

WanderersWoods_EventScript_RaniaNPC_Text_0:
# 144 "data/maps/WanderersWoods/scripts.pory"
	.string "Rania$"

WanderersWoods_EventScript_RaniaNPC_Text_1:
# 145 "data/maps/WanderersWoods/scripts.pory"
	.string "{PLAYER}! Are you headed south to\n"
	.string "Pythios Town too?\p"
	.string "Niko and I are recording Pokémon\n"
	.string "behavior around here. Every area in the\l"
	.string "Ilios Region is packed with new\l"
	.string "Pokémon!$"

WanderersWoods_EventScript_NikoNPC_Text_0:
# 155 "data/maps/WanderersWoods/scripts.pory"
	.string "Niko$"

WanderersWoods_EventScript_NikoNPC_Text_1:
# 156 "data/maps/WanderersWoods/scripts.pory"
	.string "Yia sou, {PLAYER}! Pokémon behavior\n"
	.string "is so interesting, eh?\p"
	.string "Rania and I are getting some data and\n"
	.string "training our Pokémon while we're at it!\l"
	.string "Who knows, we might beat you to Pythios\l"
	.string "Town!$"

WanderersWoods_Trigger_ChimeraEvent_Text_0:
# 178 "data/maps/WanderersWoods/scripts.pory"
	.string "Headed down to Pythios Town? We'll come\n"
	.string "with you!$"

WanderersWoods_Trigger_ChimeraEvent_Text_1:
# 183 "data/maps/WanderersWoods/scripts.pory"
	.string "There are reports of Ghost-type and\n"
	.string "Psychic-type Pokémon there. Maybe we\l"
	.string "can record some new species!$"

WanderersWoods_EventScript_ChimeraEvent_Text_0:
# 211 "data/maps/WanderersWoods/scripts.pory"
	.string "Those are Team Chimera thugs!\n"
	.string "Remember, that group who attacked the\l"
	.string "Pokédex shipment when you get here,\l"
	.string "{PLAYER}? What are they doing to\l"
	.string "those poor Pokémon?!$"

WanderersWoods_EventScript_ChimeraEvent_Text_1:
# 222 "data/maps/WanderersWoods/scripts.pory"
	.string "Chimera Grunt$"

WanderersWoods_EventScript_ChimeraEvent_Text_2:
# 223 "data/maps/WanderersWoods/scripts.pory"
	.string "Argh, nothin' like spectators to ruin a\n"
	.string "perfectly good plan. Stay out of our\l"
	.string "business!$"

WanderersWoods_EventScript_ChimeraEvent_Text_3:
# 229 "data/maps/WanderersWoods/scripts.pory"
	.string "Yeah, this doesn't concern you! The\n"
	.string "Boss is lookin' for new Pokémon for our\l"
	.string "ar-$"

WanderersWoods_EventScript_ChimeraEvent_Text_4:
# 235 "data/maps/WanderersWoods/scripts.pory"
	.string "Chimera Admin$"

WanderersWoods_EventScript_ChimeraEvent_Text_5:
# 236 "data/maps/WanderersWoods/scripts.pory"
	.string "Shut it, Grunt! Do you wanna give away\n"
	.string "all our plans?!$"

WanderersWoods_EventScript_ChimeraEvent_Text_6:
# 261 "data/maps/WanderersWoods/scripts.pory"
	.string "No! Our Pokémon got away! This is your\n"
	.string "fault... you have to pay! Grunts, let's\l"
	.string "get 'em!$"

WanderersWoods_EventScript_ChimeraEvent_Text_7:
# 268 "data/maps/WanderersWoods/scripts.pory"
	.string "We'll help you fight them, {PLAYER}!\n"
	.string "These thugs can't get away with\l"
	.string "treating Pokémon like that!$"

WanderersWoods_EventScript_ChimeraEvent_Text_8:
# 297 "data/maps/WanderersWoods/scripts.pory"
	.string "Hold it! You're not getting away!$"

WanderersWoods_EventScript_ChimeraEvent_Text_9:
# 311 "data/maps/WanderersWoods/scripts.pory"
	.string "{PLAYER}, you stay here and watch\n"
	.string "this one. I'm going after them!$"

WanderersWoods_EventScript_ChimeraEvent_Text_10:
# 321 "data/maps/WanderersWoods/scripts.pory"
	.string "I can't believe they just ran off like\n"
	.string "that! So much for loyalty.\p"
	.string "First we failed to take the Pokédex\n"
	.string "shipment, and now this... {PLAYER},\l"
	.string "right? You're becoming a real problem\l"
	.string "for Team Chimera. You'd better stay out\l"
	.string "of our business, or the Boss'll destroy\l"
	.string "you!$"

WanderersWoods_EventScript_ChimeraEvent_Text_11:
# 331 "data/maps/WanderersWoods/scripts.pory"
	.string "???$"

WanderersWoods_EventScript_ChimeraEvent_Text_12:
# 332 "data/maps/WanderersWoods/scripts.pory"
	.string "WHAT'S THIS?!$"

WanderersWoods_EventScript_ChimeraEvent_Text_13:
# 335 "data/maps/WanderersWoods/scripts.pory"
	.string "One of your friends shouted in the\n"
	.string "distance. Who was it?$"

WanderersWoods_EventScript_ChimeraEvent_Text_14:
# 358 "data/maps/WanderersWoods/scripts.pory"
	.string "Team Chimera got away from us, but look\n"
	.string "what one of them dropped! It's a\l"
	.string "{COLOR GREEN}Pokémon Egg like I've never seen\l"
	.string "before{COLOR DARK_GRAY}! Maybe it holds a rare Pokémon.\p"
	.string "{PLAYER}, I want you to have it.\n"
	.string "Pokémon Eggs aren't my specialty.$"

WanderersWoods_EventScript_ChimeraEvent_Text_15:
# 362 "data/maps/WanderersWoods/scripts.pory"
	.string "{PLAYER} received a {COLOR GREEN}Rare Egg{COLOR DARK_GRAY}!$"

WanderersWoods_EventScript_ChimeraEvent_Text_16:
# 367 "data/maps/WanderersWoods/scripts.pory"
	.string "Carry that Egg around until it hatches.\n"
	.string "Who knows, maybe it's a new species of\l"
	.string "Pokémon!\p"
	.string "Rania and I are gonna head back to the\n"
	.string "University for a while. Let us know if\l"
	.string "Pythios Town is worth a visit!$"

WanderersWoods_EventScript_ChimeraEvent_Text_17:
# 385 "data/maps/WanderersWoods/scripts.pory"
	.string "Carry that Egg around until it hatches.\n"
	.string "Who knows, maybe it's a new species of\l"
	.string "Pokémon!\p"
	.string "Niko and I are gonna head back to the\n"
	.string "University for a while. Let us know if\l"
	.string "Pythios Town is worth a visit!$"

WanderersWoods_Text_Trainer_WanderersWoods_ZanderIntro::
# 12 "data/maps/WanderersWoods/scripts.pory"
	.string "I came here for Toedscool because it's\n"
	.string "funny, but some of these Pokémon are\l"
	.string "so scary!$"

WanderersWoods_Text_Trainer_WanderersWoods_ZanderDefeat::
# 16 "data/maps/WanderersWoods/scripts.pory"
	.string "Eek! I thought I saw a Ghost Pokémon!$"

WanderersWoods_Text_Trainer_WanderersWoods_KallasIntro::
# 30 "data/maps/WanderersWoods/scripts.pory"
	.string "My Bird Pokémon and I come here to\n"
	.string "train! I'll let you help us out.$"

WanderersWoods_Text_Trainer_WanderersWoods_KallasDefeat::
# 34 "data/maps/WanderersWoods/scripts.pory"
	.string "My little birds!$"

WanderersWoods_Text_Trainer_WanderersWoods_MarthaIntro::
# 48 "data/maps/WanderersWoods/scripts.pory"
	.string "I hear some shouting up ahead. I'll stay\n"
	.string "away from there.$"

WanderersWoods_Text_Trainer_WanderersWoods_MarthaDefeat::
# 52 "data/maps/WanderersWoods/scripts.pory"
	.string "I hope it's not Team Chimera...!$"

WanderersWoods_Text_Trainer_WanderersWoods_AlexiIntro::
# 66 "data/maps/WanderersWoods/scripts.pory"
	.string "I've got a job down in Pythios Town, but\n"
	.string "now I'm lost!$"

WanderersWoods_Text_Trainer_WanderersWoods_AlexiDefeat::
# 70 "data/maps/WanderersWoods/scripts.pory"
	.string "Argh, I'm gonna be late!$"

WanderersWoods_Text_Trainer_WanderersWoods_EllieIntro::
# 84 "data/maps/WanderersWoods/scripts.pory"
	.string "I hear wild Impidimp only come out at\n"
	.string "night. So rad!$"

WanderersWoods_Text_Trainer_WanderersWoods_EllieDefeat::
# 88 "data/maps/WanderersWoods/scripts.pory"
	.string "Well that's not rad at all!$"

WanderersWoods_Text_Trainer_WanderersWoods_LydiaIntro::
# 102 "data/maps/WanderersWoods/scripts.pory"
	.string "Some Pokémon just scampered through\n"
	.string "here, like they were running from\l"
	.string "something. I wonder what happened?$"

WanderersWoods_Text_Trainer_WanderersWoods_LydiaDefeat::
# 106 "data/maps/WanderersWoods/scripts.pory"
	.string "Maybe I should've caught one.$"

WanderersWoods_Text_Trainer_WanderersWoods_ThomasIntro::
# 120 "data/maps/WanderersWoods/scripts.pory"
	.string "Pythios Town has a strange aura around\n"
	.string "it, that must be why the plants turn\l"
	.string "orange here.$"

WanderersWoods_Text_Trainer_WanderersWoods_ThomasDefeat::
# 124 "data/maps/WanderersWoods/scripts.pory"
	.string "I bet it's all the Ghost-type Pokémon.$"

WanderersWoods_Text_ChimeraAdminDefeated::
# 465 "data/maps/WanderersWoods/scripts.pory"
	.string "Beaten and stopped... the Boss won't\n"
	.string "take this.$"
