SofosCity_Acropolis_MapScripts::
	.byte 0


SofosCity_Acropolis_EventScript_Sign1::
# 5 "data/maps/SofosCity_Acropolis/scripts.pory"
	lock
# 6 "data/maps/SofosCity_Acropolis/scripts.pory"
	speakername SofosCity_Acropolis_EventScript_Sign1_Text_0
# 7 "data/maps/SofosCity_Acropolis/scripts.pory"
	msgbox SofosCity_Acropolis_EventScript_Sign1_Text_1
# 8 "data/maps/SofosCity_Acropolis/scripts.pory"
	closemessage
# 9 "data/maps/SofosCity_Acropolis/scripts.pory"
	release
	end


SofosCity_Acropolis_EventScript_Sign2::
# 14 "data/maps/SofosCity_Acropolis/scripts.pory"
	lock
# 15 "data/maps/SofosCity_Acropolis/scripts.pory"
	speakername SofosCity_Acropolis_EventScript_Sign1_Text_0
# 16 "data/maps/SofosCity_Acropolis/scripts.pory"
	msgbox SofosCity_Acropolis_EventScript_Sign2_Text_0
# 17 "data/maps/SofosCity_Acropolis/scripts.pory"
	closemessage
# 18 "data/maps/SofosCity_Acropolis/scripts.pory"
	release
	end


SofosCity_Acropolis_EventScript_Man::
# 24 "data/maps/SofosCity_Acropolis/scripts.pory"
	lock
# 25 "data/maps/SofosCity_Acropolis/scripts.pory"
	faceplayer
# 26 "data/maps/SofosCity_Acropolis/scripts.pory"
	speakername SofosCity_Acropolis_EventScript_Man_Text_0
# 27 "data/maps/SofosCity_Acropolis/scripts.pory"
	msgbox SofosCity_Acropolis_EventScript_Man_Text_1
# 28 "data/maps/SofosCity_Acropolis/scripts.pory"
	closemessage
# 29 "data/maps/SofosCity_Acropolis/scripts.pory"
	release
	end


SofosCity_Acropolis_EventScript_Camper::
# 34 "data/maps/SofosCity_Acropolis/scripts.pory"
	lock
# 35 "data/maps/SofosCity_Acropolis/scripts.pory"
	faceplayer
# 36 "data/maps/SofosCity_Acropolis/scripts.pory"
	speakername SofosCity_Acropolis_EventScript_Camper_Text_0
# 37 "data/maps/SofosCity_Acropolis/scripts.pory"
	msgbox SofosCity_Acropolis_EventScript_Camper_Text_1
# 38 "data/maps/SofosCity_Acropolis/scripts.pory"
	closemessage
# 39 "data/maps/SofosCity_Acropolis/scripts.pory"
	release
	end


SofosCity_Acropolis_EventScript_Lass::
# 44 "data/maps/SofosCity_Acropolis/scripts.pory"
	lock
# 45 "data/maps/SofosCity_Acropolis/scripts.pory"
	faceplayer
# 46 "data/maps/SofosCity_Acropolis/scripts.pory"
	speakername SofosCity_Acropolis_EventScript_Lass_Text_0
# 47 "data/maps/SofosCity_Acropolis/scripts.pory"
	msgbox SofosCity_Acropolis_EventScript_Lass_Text_1
# 48 "data/maps/SofosCity_Acropolis/scripts.pory"
	closemessage
# 49 "data/maps/SofosCity_Acropolis/scripts.pory"
	release
	end


SofosCity_Acropolis_EventScript_TogaGirl::
# 54 "data/maps/SofosCity_Acropolis/scripts.pory"
	lock
# 55 "data/maps/SofosCity_Acropolis/scripts.pory"
	faceplayer
# 56 "data/maps/SofosCity_Acropolis/scripts.pory"
	speakername SofosCity_Acropolis_EventScript_TogaGirl_Text_0
# 57 "data/maps/SofosCity_Acropolis/scripts.pory"
	msgbox SofosCity_Acropolis_EventScript_TogaGirl_Text_1
# 58 "data/maps/SofosCity_Acropolis/scripts.pory"
	closemessage
# 59 "data/maps/SofosCity_Acropolis/scripts.pory"
	release
	end


SofosCity_Acropolis_EventScript_Sign1_Text_0:
# 6 "data/maps/SofosCity_Acropolis/scripts.pory"
	.string "Information Sign$"

SofosCity_Acropolis_EventScript_Sign1_Text_1:
# 7 "data/maps/SofosCity_Acropolis/scripts.pory"
	.string "Welcome to the Sofos City Acropolis\n"
	.string "Temple, the oldest and best maintained\l"
	.string "Acropolis Temple still standing in the\l"
	.string "Ilios Region.\p"
	.string "Various statues of Pokémon with\n"
	.string "mythical origins are kept in this\l"
	.string "temple. It has become a common spot for\l"
	.string "Trainers and other tourists to come and\l"
	.string "pay respects, hoping for a blessing\l"
	.string "from these incredibly powerful Pokémon.\p"
	.string "To the left and right are statues of\n"
	.string "Archen, the First Bird Pokémon. It is\l"
	.string "thought to be the shared ancestor of\l"
	.string "all bird Pokémon, including Ho-oh and\l"
	.string "Lugia.$"

SofosCity_Acropolis_EventScript_Sign2_Text_0:
# 16 "data/maps/SofosCity_Acropolis/scripts.pory"
	.string "These Pokémon are foundational to the\n"
	.string "mythology of the Ilios Region. Left is\l"
	.string "Ho-oh, lord of the sun and fire. Right is\l"
	.string "Lugia, lord of the moon and water.\p"
	.string "According to the ancient myths of\n"
	.string "Ilios, the unending battle between\l"
	.string "these two spirits led to the\l"
	.string "manifestation of their power in the\l"
	.string "form of a Legendary Trio. Although they\l"
	.string "were once thought to be more powerful\l"
	.string "and ferocious, as the centuries passed,\l"
	.string "they transformed into more worldly\l"
	.string "forms. These modern forms are Raikou,\l"
	.string "Entei, and Suicune. More research needs\l"
	.string "to be done to find the connection to\l"
	.string "the trio's more ancient forms.$"

SofosCity_Acropolis_EventScript_Man_Text_0:
# 26 "data/maps/SofosCity_Acropolis/scripts.pory"
	.string "Tourist$"

SofosCity_Acropolis_EventScript_Man_Text_1:
# 27 "data/maps/SofosCity_Acropolis/scripts.pory"
	.string "Archen, huh? They say it evolved from a\n"
	.string "branch of reptilian Pokémon, being the\l"
	.string "first to develop feathers and wings.\p"
	.string "Of course, there are two types of\n"
	.string "evolution - Pokémon Evolution are\l"
	.string "changes from leveling up, while\l"
	.string "Biological Evolution is a process of\l"
	.string "slight changes over the course of many\l"
	.string "generations.$"

SofosCity_Acropolis_EventScript_Camper_Text_0:
# 36 "data/maps/SofosCity_Acropolis/scripts.pory"
	.string "Camper$"

SofosCity_Acropolis_EventScript_Camper_Text_1:
# 37 "data/maps/SofosCity_Acropolis/scripts.pory"
	.string "Those Pokémon from the old myths... I\n"
	.string "wonder if they're real. There are lots of\l"
	.string "parallels with stories from Johto and\l"
	.string "Kanto. I wonder if most regions have\l"
	.string "elemental Pokémon myths.$"

SofosCity_Acropolis_EventScript_Lass_Text_0:
# 46 "data/maps/SofosCity_Acropolis/scripts.pory"
	.string "Lass$"

SofosCity_Acropolis_EventScript_Lass_Text_1:
# 47 "data/maps/SofosCity_Acropolis/scripts.pory"
	.string "My family and I took a boat here from\n"
	.string "Myrrini Island. I've never seen statues\l"
	.string "like this before!$"

SofosCity_Acropolis_EventScript_TogaGirl_Text_0:
# 56 "data/maps/SofosCity_Acropolis/scripts.pory"
	.string "Toga Woman$"

SofosCity_Acropolis_EventScript_TogaGirl_Text_1:
# 57 "data/maps/SofosCity_Acropolis/scripts.pory"
	.string "Welcome. We hope you enjoy the Sofos\n"
	.string "City Acropolis Temple. Please be\l"
	.string "respectful of the fragile statues and\l"
	.string "other visitors, and enjoy your time\l"
	.string "here!$"
