SeaOfAsteri_Underwater_MapScripts::
	.byte 0


AsteriSea_Underwater_EventScript_Trainer_Underwater_Jan::
# 5 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	trainerbattle_single TRAINER_UNDERWATER_JAN, AsteriSea_Underwater_Text_Trainer_Underwater_JanIntro, AsteriSea_Underwater_Text_Trainer_Underwater_JanDefeat
# 6 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	speakername AsteriSea_Underwater_EventScript_Trainer_Underwater_Jan_Text_0
# 7 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	msgbox AsteriSea_Underwater_EventScript_Trainer_Underwater_Jan_Text_1
# 8 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	closemessage
# 9 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	release
	end


AsteriSea_Underwater_EventScript_Trainer_Underwater_Panau::
# 23 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	trainerbattle_single TRAINER_UNDERWATER_PANAU, AsteriSea_Underwater_Text_Trainer_Underwater_PanauIntro, AsteriSea_Underwater_Text_Trainer_Underwater_PanauDefeat
# 24 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	speakername AsteriSea_Underwater_EventScript_Trainer_Underwater_Panau_Text_0
# 25 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	msgbox AsteriSea_Underwater_EventScript_Trainer_Underwater_Panau_Text_1
# 26 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	closemessage
# 27 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	release
	end


AsteriSea_Underwater_EventScript_Trainer_Underwater_Yarikh::
# 41 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	trainerbattle_single TRAINER_UNDERWATER_YARIKH, AsteriSea_Underwater_Text_Trainer_Underwater_YarikhIntro, AsteriSea_Underwater_Text_Trainer_Underwater_YarikhDefeat
# 42 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	speakername AsteriSea_Underwater_EventScript_Trainer_Underwater_Yarikh_Text_0
# 43 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	msgbox AsteriSea_Underwater_EventScript_Trainer_Underwater_Yarikh_Text_1
# 44 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	closemessage
# 45 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	release
	end


AsteriSea_Underwater_EventScript_Trainer_Underwater_Weston::
# 59 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	trainerbattle_single TRAINER_UNDERWATER_WESTON, AsteriSea_Underwater_Text_Trainer_Underwater_WestonIntro, AsteriSea_Underwater_Text_Trainer_Underwater_WestonDefeat
# 60 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	speakername AsteriSea_Underwater_EventScript_Trainer_Underwater_Weston_Text_0
# 61 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	msgbox AsteriSea_Underwater_EventScript_Trainer_Underwater_Weston_Text_1
# 62 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	closemessage
# 63 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	release
	end


AsteriSea_Underwater_EventScript_Trainer_Underwater_Jan_Text_0:
# 6 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "Jan$"

AsteriSea_Underwater_EventScript_Trainer_Underwater_Jan_Text_1:
# 7 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "Pokémon can be found in the seaweed\n"
	.string "and kelp down here. They're all so\l"
	.string "amazing!$"

AsteriSea_Underwater_EventScript_Trainer_Underwater_Panau_Text_0:
# 24 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "Panau$"

AsteriSea_Underwater_EventScript_Trainer_Underwater_Panau_Text_1:
# 25 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "You can only get back to the surface\n"
	.string "where the light reaches. Otherwise, you\l"
	.string "don't know what you'd be swimming up\l"
	.string "into.$"

AsteriSea_Underwater_EventScript_Trainer_Underwater_Yarikh_Text_0:
# 42 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "Yarikh$"

AsteriSea_Underwater_EventScript_Trainer_Underwater_Yarikh_Text_1:
# 43 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "There are reports of Gyarados swimming\n"
	.string "in the depths here. That would be\l"
	.string "perfect for my team!$"

AsteriSea_Underwater_EventScript_Trainer_Underwater_Weston_Text_0:
# 60 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "Weston$"

AsteriSea_Underwater_EventScript_Trainer_Underwater_Weston_Text_1:
# 61 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "Some parts of the ocean get super deep.\n"
	.string "This area is relatively shallow, but I\l"
	.string "can't see the bottom of the Crescent\l"
	.string "Trench!$"

AsteriSea_Underwater_Text_Trainer_Underwater_JanIntro::
# 12 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "Everything has a blue tint down here.\n"
	.string "It's beautiful!$"

AsteriSea_Underwater_Text_Trainer_Underwater_JanDefeat::
# 16 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "Oh no! The beauty is ruined!$"

AsteriSea_Underwater_Text_Trainer_Underwater_PanauIntro::
# 30 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "We're beneath floating islands down\n"
	.string "here. It wouldn't be safe to surface.$"

AsteriSea_Underwater_Text_Trainer_Underwater_PanauDefeat::
# 34 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "Let's get out of here!$"

AsteriSea_Underwater_Text_Trainer_Underwater_YarikhIntro::
# 48 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "I know there's a sea serpent down here!$"

AsteriSea_Underwater_Text_Trainer_Underwater_YarikhDefeat::
# 52 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "I have to keep looking!$"

AsteriSea_Underwater_Text_Trainer_Underwater_WestonIntro::
# 66 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "The best part about living on the coast\n"
	.string "is going diving!$"

AsteriSea_Underwater_Text_Trainer_Underwater_WestonDefeat::
# 70 "data/maps/SeaOfAsteri_Underwater/scripts.pory"
	.string "Maybe I'm not as good as I thought.$"
